### ISSUE TITLE
How to add Plugin when using with React

### ISSUE THREAD

**Issue by kailashvele** [pqina/react-filepond#1]
How to register the plugins when using with react. I can see registerPlugin is imported but it is never used to register in this react wrapper. am I missing something?

**Comment by kailashvele** [comment]
Sorry it was not clear how to do it, but as registerPlugin is exported we directly call the registerPlugin(plugin-name); that solved for me. Maybe a small note in document can help. Thanks.

**Comment by rikschennink** [comment]
Should've been in the docs, will add on Monday.

**Comment by kailashvele** [comment]
Thank you.
