### ISSUE TITLE
How To Set Plugin Properties

### ISSUE THREAD

**Issue by armordog** [pqina/react-filepond#10]
### Summary
I have the image preview plugin working but I can't figure out how to set `imagePreviewMaxHeight`.

### Expected behaviour
I would expect one of these to work

- `<FilePond imagePreviewMaxHeight={1024} />`
- `<FilePond options={{ imagePreviewMaxHeight: 1024 }} />`
- `<FilePond setOptions={{ imagePreviewMaxHeight: 1024 }} />`
- `<FilePond ref={ref=>this.fp = ref} oninit={() => {this.fp.setOptions({ imagePreviewMaxHeight: 1024 })}} />`

What am I doing wrong?

**Comment by rikschennink** [comment]
This is how it should configured, it works correctly on my test install based on create-react-app

```jsx
<FilePond imagePreviewMaxHeight={100}></FilePond>
```

Maybe you're expecting a different visual result?

**Comment by armordog** [comment]
I think I was expecting something different.
Thank you for your time. =]
