### ISSUE TITLE
Gif uploads are incorrectly sent to the server

### ISSUE THREAD

**Issue by neelpalm** [pqina/react-filepond#102]
### Summary
When I upload a gif the server receives the following object:
```js
{ 
name: 'source.png',
  data: <Buffer ... >,
  encoding: '7bit',
  mimetype: 'image/png',
  mv: [Function: mv] 
}
```

I determined this is related to the Image Transform Plugin which I registered for a filepond instance elsewhere in my project. I have worked around it by setting allowImageTransform to false on this instance.

### Expected Behavior

1. I expected filetype to be unchanged even if filepond attempted to optimize images.
2. I expected registerPlugin to be tied to a particular instance vs being global.

**Comment by rikschennink** [comment]
1. The transform plugin can only export JPEG or PNG images not GIFs.

2. It currently registers them globabally and you can then disable the plugin locally.

**Comment by rikschennink** [comment]
Closed because inactive for a month
