### ISSUE TITLE
Typescript definitions doesn't include `files` prop

### ISSUE THREAD

**Issue by curtisupshall** [pqina/react-filepond#103]
### Summary
When using FilePond for React with Typescript, the example given in the README doesn't work, since the `files` property is missing from the type definitions file.

### How to reproduce
 - install `filepond` and `react-filepond`
 - include in typescript project
 - pass `files` attribute to `<FilePond>`
 - Typescript complains: ` Property 'files' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FilePond> & Readonly<FilePondProps> & Readonly<{ children?: ReactNode; }>'.`

### Expected behavior
The `files` prop should be recognized as type `files: ActualFileObject[]`

### Additional information
Here's my current workaround:

```typescript
import * as React from 'react'
import { FilePond as IFilePond, File as FilePondFile } from 'filepond-react'

export const Example = () => {
    const [files, setFiles]: [FilePondFile['file'][], 
    React.Dispatch<React.SetStateAction<FilePondFile['file'][]>>] = React.useState([])

    // From the README
    const handleFileChange = (fileItems: FilePondFile[]) => {
        setFiles(fileItems.map((fileItem: FilePondFile) => fileItem.file))
    }

    // Hackishly cast FilePond as any
    const FilePond: any = IFilePond
    return (
        <FilePond files={files} onupdatefiles={handleFileChange} />
    )
}
```

**Comment by rikschennink** [comment]
I don't maintain the TypeScript definitions so I'm not sure how to update that.

**Comment by curtisupshall** [comment]
I can see that they're created by someone else, yeah. Just thought I'd make a ticket in case he/she is still maintaining the Typescript defs. I could always give it a try, maybe... For now, the workaround is fine for those using Typescript

**Comment by rikschennink** [comment]
Closed because inactive for a month
