### ISSUE TITLE
Parent containers not resizing to suit the expanding filepond component.

### ISSUE THREAD

**Issue by michaelcuneo** [pqina/react-filepond#106]
### Summary

Not sure if this is a bug or just a usage question. No doubt a usage question... I have a React-Filepond component in my project, and if people add lots of images, the containers holding the component don't resize to suit the resizing of the react-filepond component.

### How to reproduce

By the time the Filepond component gets to be on the page, it's quite nested within wrappers and components and such, but they're all set to relative and position auto, so they should be resizing.

**Comment by rikschennink** [comment]
@michaelcuneo if sibling and wrapper element `position` properties are `static` and `width`, `height`, `top`, `left`, `bottom`, and `right` are set to `auto` then the parent element or sibling elements should scale with the filepond drop area. It sounds like you might have height restricted somewhere.

**Comment by rikschennink** [comment]
closed because inactive
