### ISSUE TITLE
Draggable image inside circle style panel layout

### ISSUE THREAD

**Issue by Ryukote** [pqina/react-filepond#107]
For example when I use

> stylePanelLayout="compact circle"

is it possible to drag an image so user can decide what part of image would be inside the circle?

I couldn't find this in documentation and in any online example.

If FilePond doesn't support this, it would be awesome if someone could implement this feature.

**Comment by rikschennink** [comment]
It doesn't support this, someone is trying this, see this related issue
https://github.com/pqina/filepond/issues/349

As an alternative you could try [Doka](https://pqina.nl/doka/) or a third party image editor
