### ISSUE TITLE
onpreparefile callback it's never been called

### ISSUE THREAD

**Issue by coluccini** [pqina/react-filepond#109]
Hi!
I'm trying to get the transformed images to handle them on the client side (I don't want to use `serve`), but the `onpreparefile` callback (the one used by @pqina in [this example](https://dev.to/pqina/generating-image-thumbnails-in-the-browser-using-javascript-and-filepond-10b8)) it's never been called.
Here a minimum working example of what i'm trying:

```javascript
import React from 'react';

import { FilePond, registerPlugin } from 'react-filepond';
import FilePondPluginImageResize from 'filepond-plugin-image-resize';
import FilePondPluginImagePreview from 'filepond-plugin-image-preview';
import FilePondPluginImageTransform from 'filepond-plugin-image-transform';
import 'filepond/dist/filepond.min.css';
import 'filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css';

registerPlugin(
  FilePondPluginImagePreview,
  FilePondPluginImageResize,
  FilePondPluginImageTransform,
);

export default () => (
  <FilePond
    imageResizeUpscale={false}
    imageResizeTargetWidth={900}
    imageResizeMode="contain"
    onaddfile={(err, fileItem) => console.log('this is called', err, fileItem.getMetadata('resize'))}
    onpreparefile={(fileItem, output) => {
      console.log('this is never been logged');
      const img = new Image();
      img.src = URL.createObjectURL(output);
      document.body.appendChild(img);
    }}
  />);
```

I'am missing something? Can you help to understand why is not triggered, please?
Thanks!

PS: I had opened another issue on the [transform plugin](https://github.com/pqina/filepond-plugin-image-transform/issues/10), but I'm closing it in favor of this one.

**Comment by coluccini** [comment]
I was using an old version 🤦‍♂️ I've updated to the latest and everything works as expected now. Sorry! 🙏

**Comment by rikschennink** [comment]
@coluccini no problem! Thanks for updating. :-)

**Comment by farhadnowzari** [comment]
It is not being called for me. 
I'm using it with the Vue component.
I can listen to addfile, removefile but not preparefile.
I'm using the filepond version 6.0.3 and doka 6.x
