### ISSUE TITLE
Feature Request / Documentation: imageEditEditor specifications for Doka

### ISSUE THREAD

**Issue by bjfresh** [pqina/react-filepond#113]
First, big thanks for a really impressive set of image / upload tools. We're really excited to implement it on our site.

### Summary

We're making use of functional components, and I'm looking for documentation on how to implement the equivalent of 

imageEditEditor: Doka.create()

when passing FilePond properties as attributes in React. It doesn't seem to work by transferring the basic implementation over directly, and I'm hoping there's an easy way to do it.

### How to reproduce

```js
      <FilePond
        // ref={ref => (this.pond = ref)}
        files={uploadedFiles}
        allowMultiple={true}
        maxFiles={10}
        server="/api" // the URL where the POST should be sent
        imageEditEditor={

        // ***** How would we invoke Doka / DokaModal from here?

            Doka.create({
            // Doka.js options here ...

            cropAspectRatioOptions: [
              {
                label: "Free",
                value: null,
              },
              {
                label: "Portrait",
                value: 1.25,
              },
              {
                label: "Square",
                value: 1,
              },
              {
                label: "Landscape",
                value: 0.75,
              },
            ],
          })
        }
      />

```

Any advice you can give is much appreciated.

**Comment by bjfresh** [comment]
Thanks, this was super helpful.

One thing I'm finding even with a minimal configuration is that Doka's markup tool is crashing.

`import React, { useState } from "react"

import * as Doka from "../../scripts/react-doka/lib/doka.esm.min"
import { FilePond, registerPlugin } from "react-filepond"
import FilePondPluginImageEdit from "filepond-plugin-image-edit"
import FilePondPluginImageExifOrientation from "filepond-plugin-image-exif-orientation"
import FilePondPluginImagePreview from "filepond-plugin-image-preview"

import "../../scripts/react-doka/lib/doka.min.css"
import "filepond/dist/filepond.min.css"
import "filepond-plugin-image-edit/dist/filepond-plugin-image-edit.css"
import "filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css"

// Register FilePond plugins
registerPlugin(
  FilePondPluginImageEdit,
  FilePondPluginImageExifOrientation,
  FilePondPluginImagePreview
)

const FileUploadField = ({ formId,field}) => {

  const { id, label, isRequired, choices } = field
  const htmlId = `input_${formId}_${id}`

  return (
    <>
      <FilePond
        imageEditEditor={
          Doka.create()
        }
      />
    </>
  )
}

export default FileUploadField
`

...crashes out with a TypeError when resizing the shapes (arrow, circle, square)
https://www.dropbox.com/s/ts4xi3l7picdy5i/doka-filepond.png?dl=0

Otherwise things seem to work fine. Any ideas as to what might be causing this issue?

Thanks again.

**Comment by rikschennink** [comment]
Is this with Doka version 5.3.2?

**Comment by bjfresh** [comment]
5.3.0

But I've just looked at the Changelog and it seems there's a new release that should fix this? We'll give it a try. Thanks for the quit reply.

**Comment by rikschennink** [comment]
Closed because inactive

**Comment by Rafcin** [comment]
Just want to reopen this for a moment. I've noticed when I use Doka to edit a image, onupdatefiles is never triggered nor is the target file itself changed. Is this something I have to handle when working with filepond? I'm essentially pushing images to a state onupdate and then sending that state out to an external state that is passed back to files={} so it can persists between multistep pages. I attempted onprepare however it runs twice and uploads the file twice and for each time it's edited, if you push to state. In the doka examples it says to use onupdatefiles however. 
```
            <FilePond

              handleChange={this.props.settings.handleChange}
              handleBlur={this.props.settings.handleBlur}

              name={this.props.settings.name}
              ref={ref => this[`${this.props.settings.name}_ref`] = ref}
              type="file"
              files={this.props.files}

              allowImagePreview={this.props.settings.allowImagePreview}
              allowMultiple={this.props.settings.allowMultiple}
              allowReorder={this.props.settings.allowReorder}
              maxFiles={this.props.settings.maxFiles}
              allowImageEdit={this.props.settings.allowImageEdit}
              acceptedFileTypes={this.props.settings.acceptedFileTypes}
              allowFileTypeValidation={this.props.settings.allowFileTypeValidation}
              allowFileSizeValidation={this.props.settings.allowFileSizeValidation}

              maxFileSize="5MB"
              labelMaxFileSizeExceeded="Files can not be larger than 5MB"
              imageEditEditor={create({
                utils: ['crop', 'filter', 'color', 'markup', 'sticker'],
              })}
              onupdatefiles={fileItems => {
                console.log(`Filepond-Ref-${this.props.settings.name} -->`, this[`${this.props.settings.name}_ref`])
                console.log(`Filepond-Ref-Images-${this.props.settings.name} -->`, fileItems.map(fileItem => fileItem.file))
                this.setState({
                  [this.props.settings.name]: fileItems.map(fileItem => fileItem.file)
                }, () => this.props.onupdatefiles(this.state[this.props.settings.name]));
              }}
            />
```

**Comment by rikschennink** [comment]
@Rafcin the internal file isn’t updated when a file is edited, only the edit instructions which are applied by image-transform before or upload.

I’d advise to maybe use the server.process method and point it to your store. It receives the modified file.

Or you can use onpreparefile, it’s called twice because the transform is also applied when the file is first dropped (with this configuration)

**Comment by Rafcin** [comment]
@rikschennink i've been considering server, however i'm not sure if I want to have it that way. I normally handle everything right at the end because this is in a form. I've tried a few things although i'm not sure what to do.

**Comment by rikschennink** [comment]
@Rafcin you don't have to actually upload the files, `server` should've been called `store` it's just the end point FilePond calls to store a file, can be in a local db, a file array, or an actual server.

**Comment by Rafcin** [comment]
@rikschennink sorry it's late so my brains slowly shutting down, but if i'm reading that correctly could I set server to say a state locally? If so that changes everything

**Comment by rikschennink** [comment]
@Rafcin No worries. Yeah, you can set each server property to a custom function and point it where ever you like.

**Comment by Rafcin** [comment]
@rikschennink how would I roughly go about setting it up to work with a local state? I'm currently reading through your server docs under advanced

**Comment by Rafcin** [comment]
I'm also thinking about just checking if the image is new or changed when onprep is called and handle it that way. I'm not sure what would be the better approach. I feel like the check will take a computational toll

**Comment by rikschennink** [comment]
it'll be fine, you can check file size

**Comment by Rafcin** [comment]
@rikschennink prep file is not the right approach it seems. Due to the second call it messes some stuff up.

**Comment by Rafcin** [comment]
Could I get the modified file from Doka and replace the old file?

**Comment by rikschennink** [comment]
you can listen to `onconfirm` and set `outputFile` to true

**Comment by Rafcin** [comment]
I tried outputFile earlier set as true and false and it still only returned the filter, crop, size details.

**Comment by Rafcin** [comment]
I downloaded the latest version of Doka just to be sure and I setup the editor just like in the React example importing the same file for create() and changing the outputFile: to true still only returns the changes done to the image and not the file

**Comment by rikschennink** [comment]
Please send a support request via customer portal, makes it a bit easier to
discuss this.

**Comment by Rafcin** [comment]
I created a ticket
