### ISSUE TITLE
display changing after building the projet

### ISSUE THREAD

**Issue by FroggDev** [pqina/react-filepond#114]
Hi,

Thanks for filepond it is a really great upload tool.

### Summary

I am facing a strange behavior:
The display works fine before building, but the display is different after building (it add an hidden overflow).

Before build
![2019-09-17 09_41_29-Window](https://user-images.githubusercontent.com/3765812/65025848-be42fa80-d937-11e9-9a39-0708fa0c559b.png)

After build
![2019-09-17 09_41_44-Window](https://user-images.githubusercontent.com/3765812/65024598-77ec9c00-d935-11e9-94dc-fbcf9a5ba7dc.png)

I checked the html code and I found the differences 
on top page code before build:
![2019-09-17 09_43_44-Window](https://user-images.githubusercontent.com/3765812/65025042-3e686080-d936-11e9-98f9-00abbf63069f.png)
on top page code before build:
![2019-09-17 09_44_38-Window](https://user-images.githubusercontent.com/3765812/65025047-41fbe780-d936-11e9-9462-940e530eab79.png)

There is something that force the parameter 

> data-state="overflow"

And when this parameter is set, the height is not set dynamically to the .filepond--hopper div.

### Additional information

I don't have any trouble on IE11 (i'am using the pollyfill)

Is there any information on what force the parameter **data-state="overflow"** i think it is the key to my trouble.

| Environment  | Version
|------------- | -----------
| OS           | Windows 
| Browser      | Opera 63 Chrome 76 Firefox 

Thanks

**Comment by rikschennink** [comment]
Sounds like you might not have set a doctype

**Comment by FroggDev** [comment]
Really fast answer thanks !

The doctype was incorrect (a <script> tag was before added automatically during the build)

With the doctype at the first line of code (where it should be) it works as it should.

Thanks a lot

![2019-09-17 11_09_33-Window](https://user-images.githubusercontent.com/3765812/65028190-f3514c00-d93b-11e9-965d-0405505cd770.png)
