### ISSUE TITLE
Example Request / Documentation: beforeDropFile hook

### ISSUE THREAD

**Issue by Shurpop** [pqina/react-filepond#118]
Hi,

I am trying to use the hook of beforeDropFile but I can't find any example of how to use it.

Please, could be possible to add a full example of it? 

Otherwise, when I try to use it with typescript I am unable to get the property...

Thanks!

**Comment by rikschennink** [comment]
Hi,

```jsx
<FilePond beforeDropFile={
    (file) => {
        // return either true or false depending on the file
    }
}/>
```

**Comment by Shurpop** [comment]
Hi!

We found the problem was in the imported types of typescript.

Using jsx file works correctly :)

"react-filepond": "^7.0.1",
"@types/react-filepond": "^5.0.4",

Could be possible to update the types with the latests changes? 

Thanks for your fast answer :+1:

**Comment by rikschennink** [comment]
Ah, PR is welcome
