### ISSUE TITLE
Image transform don't work

### ISSUE THREAD

**Issue by sinclaireric** [pqina/react-filepond#119]
hi , i need your help, selected image can't be resized before upload to the server

`import { FilePond, File, registerPlugin } from 'react-filepond';
import FilePondPluginImageResize from 'filepond-plugin-image-resize';
import FilePondPluginImageValidateSize from 'filepond-plugin-image-validate-size';
import FilePondPluginFileValidateSize from 'filepond-plugin-file-validate-size';
import 'filepond/dist/filepond.min.css';
import FilePondPluginImagePreview from 'filepond-plugin-image-preview';
import 'filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css';
import FilePondPluginImageTransform from 'filepond-plugin-image-transform';
registerPlugin(FilePondPluginImageResize,
FilePondPluginImagePreview,
FilePondPluginImageValidateSize,
FilePondPluginFileValidateSize,
FilePondPluginImageTransform
);`

`<FilePond

          files={this.state.thumb}
          allowMultiple={false}

          allowImagePreview={true}
                              imageValidateSizeMinWidth={200}
                              imageValidateSizeMinHeight={200}
                              imageValidateSizeMaxWidth={8000}
                              imageValidateSizeMaxHeight={8000}
                              imageResizeTargetWidth={1300}
                              imageResizeTargetHeight={700}
                              imageResizeUpscale={false}
                              maxFileSize={'3MB'}
                              allowImageTransform={true}
                              imageTransformOutputQuality={65}

          acceptedFileTypes={['image/*']}
          labelFileTypeNotAllowed="Envoyez un fichier image"
          labelIdle='<span class="filepond--label-action">Choisir une image</span>'

          onupdatefiles={(fileItems) => {
              // Set current file objects to this.state
              this.setState({
                  thumb: fileItems.map(fileItem => fileItem.file)
              });

          }}

>
</FilePond>`

**Comment by rikschennink** [comment]
Please format your issue.
