### ISSUE TITLE
adding user supplied values to payload

### ISSUE THREAD

**Issue by indefinitelee** [pqina/react-filepond#12]
How can I add some user supplied values along with the file payload sent to my server? 
for example, my users will need to add a file and then input some values such as 

```js
{
  client: "Acme Inc.", 
  clientId: 123, 
}
```

i can easily add some input fields and clickHandlers to get those values into state, but not sure how to get FilePond to access them and send to backend. 

thanks

**Comment by rikschennink** [comment]
I think that will take the initial state value and copy it to files, if the state updates the metadata will not.

I think calling setMetadata on each file after the state updates would be better if you want the latest value.

**Comment by LeviStrange** [comment]
Hi, I am struggling to add user form data to a file upload. How can I do this?

**Comment by rikschennink** [comment]
@LeviStrange please don't double post.
