### ISSUE TITLE
Percentage complete not updating when using custom process with AWS Storage API

### ISSUE THREAD

**Issue by dupreezc** [pqina/react-filepond#120]
### Summary
Great product !! Thank you.

Using react library.
Using a custom server process - AWS Storage API  the percentage complete does not update. I do make a call to progress with the relevant parameters. I can confirm that this call fires.

### How to reproduce
Plugins Registered

```
registerPlugin(FilePondPluginImageExifOrientation, FilePondPluginImagePreview);

```
Filepond component.
```
<div className="App">
        {/* Pass FilePond properties as attributes */}
        <FilePond
          ref={ref => (this.pond = ref)}
          files={this.state.files}
          allowMultiple={true}
          maxFiles={3}
          server={{
            process: (fieldName, file, metadata, load, error, progress, abort) => {
              this.handleProcessing(fieldName, file, metadata, load, error, progress, abort);
            },
          }}
          oninit={() => this.handleInit()}
          onupdatefiles={(fileItems) => {
            // Set currently active file objects to this.state
            this.setState({
              files: fileItems.map(fileItem => fileItem.file)
            });
          }}
        />
      </div>
```
Processing handler

```
handleProcessing(fieldName, file, metadata, load, error, progress, abort) {
 
  const filename = `${Date.now()}-${file.name}`;
  Storage.vault.put(filename, file, {
    contentType: file.type,
    progressCallback: (progress) => {
      console.log(progress);
      progress(progress.lengthComputable, progress.loaded, progress.total);
    },
      })
      .then( result => {console.log (result); load(result.key)})
      .catch( err => error(err.message));
}

```
The console log produces the upload stats and progress is called.
### Expected behaviour
I expect the process indicator to show percentage complete as the upload progress. Not just the spinning circle. The upload completes successfully.

### Additional information

| Environment  | Version
|------------- | -----------
| OS           | MacOS
| Browser      | Chrome Version 77.0.3865.120 (Official Build) (64-bit)

**Comment by rikschennink** [comment]
Does this property `progress.lengthComputable` contain `true`?

**Comment by dupreezc** [comment]
Hi, yes it does.

**Comment by rikschennink** [comment]
I'm not sure why it doesn't work then. Please create a public test code on codesandbox.io, happy to take a look.

**Comment by dupreezc** [comment]
Thank you. I will do

**Comment by dupreezc** [comment]
Problem solved !

Oversight on my side - apologies.

changed this code 

```
progressCallback: (progress) => {
      console.log(progress);
      progress(progress.lengthComputable, progress.loaded, progress.total);
    },
```

to this 

```
progressCallback: (prog) => {
      // console.log(progress);
      progress(prog.lengthComputable, prog.loaded, prog.total);
    },
```
progress param was redefining progress function

**Comment by rikschennink** [comment]
@dupreezc ah yes, good one! I think we've all been there ;-)
