### ISSUE TITLE
onprocessfile event objects are swapped around.

### ISSUE THREAD

**Issue by samcarton** [pqina/react-filepond#121]
### Summary
When handling the `onprocessfile` event, the `file: File` and `error: FilePondErrorDescription` objects actually receive the opposite objects (i.e. the error details go to `file`, and the file details go to `error`).

### How to reproduce
See https://codesandbox.io/s/runtime-morning-yc7xu

### Expected behaviour
`file: File` should have the successful file upload details. `error` should only contain the error details as per the event spec.

### Additional information

| Environment  | Version
|------------- | -----------
| OS           |  Windows
| Device       | Desktop
| Browser      | Chrome 77.0.3865.120

**Comment by rikschennink** [comment]
The first argument should be the error or `null`, see docs, https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#callbacks

Not sure why it shows differently in the sandbox.

**Comment by samcarton** [comment]
Thanks for the immediate reply.
Am I right in assuming it may be the typescript definition is wrong? 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/807f5db1633cba3e7b90b11314fa5da469aac42d/types/react-filepond/index.d.ts#L326

**Comment by samcarton** [comment]
Interestingly there's a comment above that export

> Note that in my testing, callbacks that include an error prop always give the error as the second prop, with the file as the first prop.    This is contradictory to the current docs.
I'll chase it up over on that repo. Thanks again!

**Comment by samcarton** [comment]
I have raised an issue over there: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/40152
