### ISSUE TITLE
acceptedFileTypes doesn't work

### ISSUE THREAD

**Issue by aaveidt** [pqina/react-filepond#124]
```
<FilePond
          allowMultiple={false}
          allowFileTypeValidation={true}
          labelFileTypeNotAllowed="Invalid File"
          acceptedFileTypes={['image/*']}
          server={{
            url: G.baseURL + '/' + G.adminRootURL() + '/upload',
            process: {
              headers: {
                Authorization: `Bearer ${sessionStorage.getItem('token')}`,
              },
              onload: response => {
                response = JSON.parse(response)
                this.finishedUpload(response.data)
              },
            },
          }}
          onaddfilestart={e => this.change(e)}
          // onprocessfile={(e, file) => this.finishedUpload(e, file)}
          onremovefile={file => this.removeUploadedFile(file)}
        />
```
Then i uploaded any file, they're all work.
Testing on Chrome 78.0, macos

**Comment by rikschennink** [comment]
Closed because doesn't match issue template and unclear what the problem is.

**Comment by aaveidt** [comment]
It's simple, above code doesn't work properly. 
Instead of giving invalid file error, it allows to upload any file.
Already mentioned #79 

ps: If you don't wanna solve it, just close it. Giving Issue template reason doesn't help here.

**Comment by rikschennink** [comment]
Have you registered the file validate type plugin

**Comment by mgallegoccxc** [comment]
@aaveidt I found this solution https://www.npmjs.com/package/filepond-plugin-file-validate-type, i hopes help you

**Comment by aaveidt** [comment]
@mgallegoccxc thank you, it works. I didn't intergrate this plugin

**Comment by masbaehr** [comment]
Hey why was this closed? It simply does not work. And installing a plugin to fix this and adding yet another dependency is NOT a decent solution. 

The correct solution would be the following to make it work on most OS/Browsers:

Pass the "Accept" property correctly to the filepond object:

JS-Workaround Example which will allow to select only images
document.getElementsByClassName("filepond--browser")[0].setAttribute("Accept", "image/*")

Having said that  acceptedFileTypes={['image/*']}  filepond property should do that too.

**Comment by rikschennink** [comment]
@masbaehr that's exactly what the separate plugin is for.
