### ISSUE TITLE
Retrieve filename after uploading

### ISSUE THREAD

**Issue by avillarubia** [pqina/react-filepond#125]
### Summary
Good day guys
Beginner here in filepond.
I am using react filepond with node js server that uses multer. 
The uploading is successful that in the server it saves and renames into a **binary file without extension** something like this **1be244f42f4e9fc5c52890b14b441234** original filename let say was boys.jpg.

I guess renaming is not a problem.
```
      const [files, setFiles] = useState([])
      return (
        <FilePond
            name='images'
            files={files}
            allowMultiple={false}
            onupdatefiles={setFiles}
            onprocessfile={(error, file) => {
                console.log("id", file.id)
                console.log("server id", file.serverId)
                console.log("origin", file.origin)
                console.log("file", file.file)
                console.log("fileExtension", file.fileExtension)
                console.log("fileSize", file.fileSize)
                console.log("filename", file.filename)
                console.log("filenameWithoutExtension", file.filenameWithoutExtension)
            }}
            labelIdle='Drag & Drop your files or <span class="filepond--label-action">Browse</span>'
            server='http://localhost:3000/api/uploads'
        />)
```

### Expected behavior
Now, I am looking for help maybe you guys already encounter this.

**I want to get the file in binary name** but the line 
`console.log("id", file.id)` 
returns like 6-10 chars so that's not what I looking for.
**I guess it should be the file.serverId but returns empty**.

Another one is I am not sure if **binary or the filename** is to use when GET a file from the server then display it on react app. That is what I planned to do.
 
### Additional information

| Tools                                              | Version
|------------------------------------- | -----------
| CLIENT
| React                                             | 16.9.0
| react-filepond                               | 7.0.1
| filepond-plugin-file-encode         | 2.1.4
| filepond-plugin-image-preview   | 4.5.0
| filepond-plugin-image-resize       | 2.0.4
| SERVER
| node                                              | 12.13.1
| multer                                            | 1.4.2
| ENVIRONMENT
| OS                                                 | Windows 10 Pro
| Browser                                         | Chrome 79.0.3945.79

Thank you for all the responses.

**Comment by rikschennink** [comment]
FilePond pushes both a JSON string and a file object to the server (under same field name), so make sure Multer is saving the file object. The POST to `http://localhost:3000/api/uploads` should return a plain/text response containing the id of the file on the server. This id will then appear in the `file.serverId` property.

**Comment by avillarubia** [comment]
@rikschennink thank you for all the responses,

I have only a few lines on the server-side

```
const uploadOptions = { dest: 'public/uploads/' }
const upload = multer(uploadOptions)

router.post("/", upload.single('images'), (req, res) => {
    res.send()
})
```
it successfully saves the file

for now, this confuses me to where I can send back the serverId since the generation of serverId happens inside on middleware part.

I should put it on question portion, not an issue, I don't see a place to post this sorry about that.

btw @rikschennink I am the guy asking you on twitter named aljohn.
I repost this question for documentation and to share with others that this topic may help them in the future.

**Comment by avillarubia** [comment]
I found the problem, that is when adding the lines below
```
const mimeTypes = ['image/jpeg']

const uploadOptions = {
    dest: 'public/uploads/',
    fileFilter: (req, file, callback) => {
        callback(mimeTypes.includes(file.mimetype))
    }
}

const upload = multer(uploadOptions)
```
on fileFilter part that makes req.file return undefined. But now it contains details with binary name I am searching. With the line below,

   **res.send(req.file.filename)**

on react app it returns now the binary name
![image](https://user-images.githubusercontent.com/37901895/71316580-a5a12e00-24ac-11ea-911f-108afc74b775.png)

thank you a lot @rikschennink
