### ISSUE TITLE
Duplicate file uploaded

### ISSUE THREAD

**Issue by avillarubia** [pqina/react-filepond#126]
### Summary
Good day guys,
Good day @rikschennink 

I guess I got a bug but I am not sure yet.
Sometimes when I upload a single file it duplicates in the server.

```
    const [files, setFiles] = useState([])

    function setMetadata(fileItems) {
         return fileItems.map(fileItem => fileItem.setMetadata('username', 'yourUserName'))
    }

    return <>
        <FilePond
            acceptedFileTypes={['image/jpeg']}
            name='images'
            files={files}
            allowMultiple={false}
            onupdatefiles={fileItems => { setFiles(setMetadata(fileItems)) }}
            onprocessfile={(error, file) => {
                console.log("server id", file.serverId)
            }}
            labelIdle='Drag & Drop (jpg) files or <span class="filepond--label-action">Browse</span>'
            server='http://localhost:3000/api/uploads/'
        />
    </>
```
server-side lines of codes
```
const mimeTypes = ['image/jpeg']

const storage = multer.diskStorage({
    destination: function (req, file, cb) {
        cb(null, 'public/uploads/')
    },
    filename: function (req, file, cb) {
        cb(null, Date.now() + '_' + file.originalname)
    }
})

const upload = multer({
    storage: storage,
    fileFilter: (req, file, cb) => {
        const isAccepted = mimeTypes.includes(file.mimetype)
        cb(null, isAccepted)
    }
})

router.post("/", upload.single('images'), ({ file, body }, res) => {
    if (!file) return res.send("File uploaded not supported.")
    res.send(file.filename)
})
```

### Expected behavior
I only upload a single file and don't allow any multiple uploads. So the expected result should be a single file in the server that uses multer.

### Additional information
On adding the file before the counter starts at 0% (upload status) sometimes the file is saved on the server. Then, when 100% reaches then another same file is added.

| Tools                                              | Version
|------------------------------------- | -----------
| CLIENT
| React                                             | 16.9.0
| react-filepond                               | 7.0.1
| filepond-plugin-file-encode         | 2.1.4
| filepond-plugin-image-preview   | 4.5.0
| filepond-plugin-image-resize       | 2.0.4
| filepond-plugin-file-type              | 2.0.4
| SERVER
| node                                              | 12.13.1
| multer                                            | 1.4.2
| ENVIRONMENT
| OS                                                 | Windows 10 Pro
| Browser                                         | Chrome 79.0.3945.79

Thank you for all the responses.

**Comment by rikschennink** [comment]
Thanks for the detailed issue report. Do you see multiple files being submitted in your developer tools network tab?

**Comment by avillarubia** [comment]
I try only one jpeg format, in the network tab I only see one in that format

**Comment by rikschennink** [comment]
In that case the duplication probably happens on your server.

**Comment by avillarubia** [comment]
@rikschennink thank you for the response I guess you're right, perhaps I didn't see the problem in my server side for now I set **instant upload to false**
