### ISSUE TITLE
Sometimes auto upload doesn't work

### ISSUE THREAD

**Issue by avillarubia** [pqina/react-filepond#127]
### Summary
Good day guys,
Good day @rikschennink 

### Expected behavior
![image](https://user-images.githubusercontent.com/37901895/71339623-01dc7e80-258f-11ea-9127-7dbac3e150d6.png)

Sometimes it starts counting the upload status sometimes not.

Here are some lines that might be helpful for investigation.

```
    const [files, setFiles] = useState([])

   function setMetadata(fileItems) {
         return fileItems.map(fileItem => fileItem.setMetadata('username', 'yourUserName'))
  }

    return <>
        <FilePond
            acceptedFileTypes={['image/jpeg']}
            name='images'
            files={files}
            allowMultiple={false}
            onupdatefiles={fileItems => { setFiles(setMetadata(fileItems)) }}
            onprocessfile={(error, file) => {
                console.log("server id", file.serverId)
            }}
            labelIdle='Drag & Drop (jpg) files or <span class="filepond--label-action">Browse</span>'
            server='http://localhost:3000/api/uploads/'
        />
    </>
```

### Additional information

| Tools                                              | Version
|------------------------------------- | -----------
| CLIENT
| React                                             | 16.9.0
| react-filepond                               | 7.0.1
| filepond-plugin-file-encode         | 2.1.4
| filepond-plugin-image-preview   | 4.5.0
| filepond-plugin-image-resize       | 2.0.4
| filepond-plugin-file-type              | 2.0.4
| SERVER
| node                                              | 12.13.1
| multer                                            | 1.4.2
| ENVIRONMENT
| OS                                                 | Windows 10 Pro
| Browser                                         | Chrome 79.0.3945.79

Thank you for all the responses.

**Comment by rikschennink** [comment]
Can you supply a test case on codesandbox.io ?

**Comment by avillarubia** [comment]
@rikschennink here
https://codesandbox.io/s/react-filepond-yo919

**Comment by rikschennink** [comment]
@avillarubia it doesn't run.

```
A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.
```

**Comment by avillarubia** [comment]
@rikschennink runs perfectly fine in my side, I will check it

**Comment by avillarubia** [comment]
Merry Christmas @rikschennink 

done fixing, kindly check it on your side?

![image](https://user-images.githubusercontent.com/37901895/71431733-cbc60880-270e-11ea-8aaf-18cd240305df.png)

**Comment by rikschennink** [comment]
I think you need to run this in `onaddfile`

```js
fileItem.setMetadata("username", "yourUserName");
```

`onupdatefiles` is only there to sync the react state with the filepond state.

**Comment by ShahNewazKhan** [comment]
hi @rikschennink my `onaddfile` callback always has an empty `file` object, how can I retrieve the details of the file being loaded at this juncture?

**Comment by rikschennink** [comment]
@ShahNewazKhan the function receives two parameters, `error` and `fileitem`, see docs.

**Comment by ShahNewazKhan** [comment]
> @ShahNewazKhan the function receives two parameters, `error` and `fileitem`, see docs.

Thanks for getting back, console logging the second parameter as follows shows an empty strigified object, however I can access the `file.name` attribute. 

```
...
onaddfile = (error, file) =>{
   console.log( JSON.stringify(file) )
   console.log( JSON.stringify(file.name) )
}
...
```

**Comment by rikschennink** [comment]
@ShahNewazKhan https://pqina.nl/filepond/docs/patterns/api/file/

**Comment by avillarubia** [comment]
@rikschennink as always thank you, for now, I am using **instantUpload={false}** the upload will trigger when a button is hit.
