### ISSUE TITLE
Render Pdf-component from onaddfile ?

### ISSUE THREAD

**Issue by burton666** [pqina/react-filepond#128]
I would like to add previews when adding pdf-files and have a pdf-viewer-component for that reason. But how do I render another component from within the Filepond component?

```jsx
 <FilePond
        acceptedFileTypes={["image/*", "application/pdf"]}
        allowImagePreview={true}
        imagePreviewHeight={840}
        server={"http://localhost:3001/api/upload"}
        instantUpload={true}
        files={files}
        allowMultiple={false}
        onupdatefiles={setFiles}
        labelIdle='Drag & Drop your files or <span class="filepond--label-action">Browse</span>'
        onaddfile={ (error, file) => {
            if(file.fileExtension === 'pdf'){
              return <PDF-Viewer />
            }
        }}
      />
```

**Comment by rikschennink** [comment]
You can create a plugin, see the [image preview plugin](https://github.com/pqina/filepond-plugin-image-preview) for an example.

You could also decide to help @nielsboogaard who's working on the [media preview plugin](https://github.com/nielsboogaard/filepond-plugin-media-preview)

**Comment by burton666** [comment]
Ok, thanks but that is beyond my knowledge. If I instead would try to use some javascript to generate an image of the pdf-file in the onaddfile-function. Could I somehow insert that image in the preview-plugin but still upload the pdf-file?

**Comment by rikschennink** [comment]
I think the image poster plugin would be the easiest approach but the image needs to be available on load so I don't you can add it later without altering the plugin code.

**Comment by ErnestBrandi** [comment]
Hi, just letting you guys know I made a quick fork of @nielsboogaard media-preview plugin which also previews pdf. 
https://github.com/ErnestBrandi/filepond-plugin-media-preview

**Comment by rikschennink** [comment]
@ErnestBrandi thanks! will add it to the list 👍
