### ISSUE TITLE
suggestion : put sandbox code into npm quick start 

### ISSUE THREAD

**Issue by vianneyguesdon** [pqina/react-filepond#129]
Hello,

The npm doc is outdated and is very hard to work with, especially in typescrypt. I found the sandbox demo much easier to implement. Would be nice to put it into npm to drive adoption. I guess most people give up after trying the npm doc. I almost did.

This is the component I used

import React, { useState } from "react";
import { FilePond, registerPlugin } from "react-filepond";

import "filepond/dist/filepond.min.css";

import FilePondPluginImageExifOrientation from "filepond-plugin-image-exif-orientation";
import FilePondPluginImagePreview from "filepond-plugin-image-preview";
import "filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css";

registerPlugin(FilePondPluginImageExifOrientation, FilePondPluginImagePreview);

function App() {
  const [files, setFiles] = useState([]);
  return (
    <div className="App">
      <FilePond
        files={files}
        allowMultiple={true}
        onupdatefiles={setFiles}
        labelIdle='Drag & Drop your files or <span class="filepond--label-action">Browse</span>'
      />
    </div>
  );
}

**Comment by rikschennink** [comment]
Do you mean readme.md?

**Comment by vianneyguesdon** [comment]
yes exactly. I think the code below "usage" in npm is confusing. Plus it's a class based component, I would rather see the new version of React with hooks.

**Comment by rikschennink** [comment]
PR is welcome

**Comment by rikschennink** [comment]
Done
