### ISSUE TITLE
Pass name prop to <input/>

### ISSUE THREAD

**Issue by vitordino** [pqina/react-filepond#13]
first of all, congratulations on this amazing component 😄 

besides accessibility, there are some services that use the `name` property on form elements — e.g. [netlify](https://netlify.com/)

so if we could just pass this string down, it'll be a huge plus ✌️

**Comment by vitordino** [comment]
ps: i'm a true believer of [JAMStack](https://jamstack.org/) for small sites, so i'm really looking forward to integrate it on netlify's built in [form handling](https://www.netlify.com/blog/2017/07/20/how-to-integrate-netlifys-form-handling-in-a-react-app/).

if you have any idea for doing this, please light me the way because i'm not really good on understanding these backend details — i did read the documentation, including the _server_ section, but i couldn't solve it right away

**Comment by rikschennink** [comment]
Hi! Glad to hear you like it!

The `<input/>` is not being submitted, it's basically only there to expose the "browse file system" functionality.

If you're uploading async, the `name` property is used as the name of the field that is posted to the server. If you're using the file encode plugin the `name` attribute is added to the hidden input elements that contain the encoded file data.
