### ISSUE TITLE
Unable to set URL on FilePond instance using setOptions

### ISSUE THREAD

**Issue by erickco** [pqina/react-filepond#131]
### Summary
I am uploading a file to Google app engine using FilePond in react. When a file is selected, I need to fetch an upload URL (which has a short life) from the server before uploading. 

Based on the FilePond docs I think I need to do the following steps:
 - disable instantUpload

 - handle the onaddfilestart callback

 - in the callback handler
       - fetch the upload URL (I use axios)
       - set the 'server' attribute in FilePond instance to the URL using setOptions
       - call processFile on the FilePond instance to upload

### How to reproduce
I'm using a react Component class, so my code has:

In constructor:
``` javascript
this.pond = React.createRef();
```
in render:
``` javascript
      <FilePond ref={this.pond}
                        onaddfilestart={this.handleAddFileStart }
                        instantUpload={false}/>
```

in handleAddFileStart
``` javascript
        axios.get('/get_upload_url')
        .then( response => {

            this.pond.setOptions({
                server: response.data.upload_url,
            });
            
            this.pond.processFile().then(file => {
                console.log('File uploaded just fine')
            });

        } )
        .catch( error => {
            console.log(error)
        } );
```

I get 
```
TypeError: this.pond.setOptions is not a function
```
I can off-course fetch the upload URL before the render method is called and set the server attribute on the FilePond component in JSX. But since the upload link expires after a few minutes I need a fresh link when an upload is triggered by the user.

### Expected behaviour
I would like to be able to set the server URL in the FilePond instance after a file has been dropped/selected and then trigger the upload.

### Additional information
I looked at the following similar issues, but don't see an answer that works for me 
https://github.com/pqina/react-filepond/issues/40
https://github.com/pqina/react-filepond/issues/54

| Environment  | Version
|------------- | -----------
| OS           | MacOS 
| Browser      | Chrome 80.0.3987.149 (Official Build) (64-bit)

**Comment by rikschennink** [comment]
I think you can simply define a static server property and use a custom process method, in the process method you first request the upload URL and then you upload the file.

**Comment by erickco** [comment]
> I think you can simply define a static server property and use a custom process method, in the process method you first request the upload URL and then you upload the file.

Thanks Rik. Does that mean my custom process method takes responsibility for the upload as well? I would like to use the FilePond processing capability if possible since it updates the UI (i.e. success / error feedback etc.)

**Comment by rikschennink** [comment]
Yeah it'll also have the upload, but if you correctly run the callback methods that FilePond passes to your custom process method then the UI will be updated accordingly.
