### ISSUE TITLE
Memory issue in uploading large sized images

### ISSUE THREAD

**Issue by ubaid-rehman74** [pqina/react-filepond#136]
### Summary
I am facing memory problems with large sized files. I uploaded 60 large sized images. Each image is 46MB in size. First my browser stuck in loading state then my browser crashed before uploading. Is there any way to overcome this behavior?

Screenshot here.

<img width="1440" alt="Screenshot 2020-06-02 at 4 05 46 PM" src="https://user-images.githubusercontent.com/66308988/83513256-f2247700-a4ea-11ea-9603-6027717d7643.png">

### How to reproduce
Upload more than 60 images, each with size greater than 50MB.

### Expected behaviour
All large sized images should upload without any problem

| Environment  | Version
|------------- | -----------
| OS           | MacOS Catalina
| Browser      | Chrome

**Comment by rikschennink** [comment]
Are you uploading encoded images? or uploading asynchronously?

**Comment by ubaid-rehman74** [comment]
> Are you uploading encoded images? or uploading asynchronously?

Asynchronously.

**Comment by rikschennink** [comment]
Are you manipulating the images (cropping etc)? Do you have preview enabled?

**Comment by ubaid-rehman74** [comment]
I'm not cropping images and Yes, preview is enabled

Here are some of the settings

allowMultiple={true}
acceptedFileTypes={['image/*']}
imagePreviewMaxHeight={150}
allowImageTransform={false}
allowImageResize={true}
imageResizeUpscale={false}
imageResizeMode="contain"
allowRevert={true}
maxParallelUploads={200}
itemInsertInterval={1}
imageValidateSizeMinWidth='300'
imageValidateSizeMinHeight='300'
maxFileSize='70MB'
chunkUploads={true}
labelFileProcessingError="Invalid file"
labelFileProcessingComplete="Ready"


Also tried this

allowMultiple={true}
acceptedFileTypes={['image/*']}
allowFileTypeValidation={true}
allowFileEncode={true}
imagePreviewMaxHeight={150}
imageValidateSizeMinWidth='300'
imageValidateSizeMinHeight='300'
maxFileSize='70MB'
chunkUploads={true}
labelFileProcessingError="Invalid file"
labelFileProcessingComplete="Ready"

**Comment by ubaid-rehman74** [comment]
These are the plugins I used

registerPlugin(
  FilePondPluginImagePreview,
  FilePondPluginFileValidateSize,
  FilePondPluginFileValidateType,
  FilePondPluginImageValidateSize,
  FilePondPluginImageExifOrientation
);

**Comment by ubaid-rehman74** [comment]
@rikschennink you can also reproduce it here by uploading 60-70 images with 50MB each in size
https://codesandbox.io/s/github/KimGenius/React-file-pond/tree/master/

Here is the output

<img width="1440" alt="Screenshot 2020-06-02 at 5 48 07 PM" src="https://user-images.githubusercontent.com/66308988/83522063-8d244d80-a4f9-11ea-88fb-bab535914866.png">

**Comment by rikschennink** [comment]
I suspect it's just too much data for the browser to handle. Each image will be drawn to a preview canvas, so that's a lot of canvas elements, maybe it exceeds the max amount the browser can assign to canvas data, I know there's a hard limit on Safari.

I'm wondering if removing the FilePondPluginImageExifOrientation plugin makes any difference.

**Comment by rikschennink** [comment]
closed because inactive
