### ISSUE TITLE
How to add formdata key?

### ISSUE THREAD

**Issue by AlexandrDobrovolskiy** [pqina/react-filepond#14]
![image](https://user-images.githubusercontent.com/23122290/45260458-1116d780-b3f1-11e8-91b6-1e27f51fd33e.png)
This is how I upload files manually, can I configure the special key "news" for form-data?
Using React.

**Comment by rikschennink** [comment]
I'm not sure where this code is located in relation to FilePond.

If you're wondering if you can set the field name when using FilePond, then yes, you can supply a name attribute and FilePond will automatically add it in a manner similar to what you've outlined above.
