### ISSUE TITLE
Array Filename Same Problem

### ISSUE THREAD

**Issue by uqurtosun** [pqina/react-filepond#140]
Hello,
 
My Example Code;

![oragne](https://user-images.githubusercontent.com/54816750/86562798-f9b4c100-bf6b-11ea-9971-d11926ee773a.png)

Output;

All Upload File Name Write : Orange

Your check image problem :
**BEFORE**
![2](https://user-images.githubusercontent.com/54816750/86562286-20262c80-bf6b-11ea-8919-062db06d6a7e.png)

**AFTER**
![Screen_Shot_2020-07-06_at_09 21 12](https://user-images.githubusercontent.com/54816750/86561904-629b3980-bf6a-11ea-8985-06475a21931d.png)

**Comment by rikschennink** [comment]
The `FilePond` component doesn't expose a `fileName` property.

**Comment by uqurtosun** [comment]
> The `FilePond` component doesn't expose a `fileName` property.

I know, but how else can I do this?

**Comment by rikschennink** [comment]
You'll need to use the file rename plugin:

https://pqina.nl/filepond/docs/patterns/plugins/file-rename/

**Comment by uqurtosun** [comment]
I already made this setting. is that wrong ?

![newimage](https://user-images.githubusercontent.com/54816750/86564264-98422180-bf6e-11ea-8ddc-e8cfecff6936.png)

**Comment by uqurtosun** [comment]
> You'll need to use the file rename plugin:
> 
> https://pqina.nl/filepond/docs/patterns/plugins/file-rename/

I already made this setting. is that wrong ?

![newimage](https://user-images.githubusercontent.com/54816750/86566057-a5acdb00-bf71-11ea-9141-18742073886a.png)

**Comment by rikschennink** [comment]
I'd put a log statement inside to see if the code runs
