### ISSUE TITLE
How can I use filepond-plugin-file-rename

### ISSUE THREAD

**Issue by uqurtosun** [pqina/react-filepond#141]
I already made this setting. is that wrong ?
 
![newimage](https://user-images.githubusercontent.com/54816750/86573404-08f03a80-bf7d-11ea-9cac-25c0d56a4311.png)

![bla3](https://user-images.githubusercontent.com/54816750/86575014-4a81e500-bf7f-11ea-85dd-d974858c2c01.png)

![bla1](https://user-images.githubusercontent.com/54816750/86574801-0d1d5780-bf7f-11ea-864d-86c59c12e523.png)

![bla2](https://user-images.githubusercontent.com/54816750/86574810-13abcf00-bf7f-11ea-97a1-27d52bba0c89.png)

**Comment by rikschennink** [comment]
Please don't double post

**Comment by uqurtosun** [comment]
> Please don't double post

I used this plugin at every stage of the project. And it can't solve the problem. I have to deliver the project.

It takes only one value if I use it in different components
