### ISSUE TITLE
How to distinguish local file and newly uploaded file?

### ISSUE THREAD

**Issue by serendipity1004** [pqina/react-filepond#144]
I am setting local file with options like below using React.useState.

```
[{
  source:fileUrl,
  options: {
    type: 'local',
    metadata: {
      poster: fileUrl,
    }
   }
}]
```

However, once Filepond loads, I am unable to get the value `filles[0].options.type`. The local file is turned into a blob and does not maintain the option values. I would like to be able to know which of the files are newly uploaded file so that I can send only corresponding files to the server.

**Comment by rikschennink** [comment]
https://pqina.nl/filepond/docs/patterns/api/file/

The `origin` property.
