### ISSUE TITLE
Filepond as Controlled Component

### ISSUE THREAD

**Issue by jacklimwenjie** [pqina/react-filepond#145]
I'm trying to make `Filepond` a controlled component. Just to make sure we are on the same page, [this](https://reactjs.org/docs/forms.html#controlled-components) is what I meant by controlled component. 

In short, I'm trying to use the `files` prop and the `onupdatefiles` prop like what the `value` prop and the `onChange` prop is to an `<input>` element. This is to enable populating the files uploaded by feeding the `files` props some data initially, and when files are added or removed, to callback with the latest file list. 

Here's a sandbox to illustrate what I was describing: https://codesandbox.io/s/confident-cloud-jgj23?file=/src/App.js

Everything is working fine, except that when I programmatically set the `files` state, such that the initial file is removed from the state, the `remove` server custom method is invoked for that initial file. You can reproduce this by clicking either the "Empty files state" button or the "Swap file" button. Both will result in a console log message "remove" because the `remove` server method is hooked to nothing but a `console.log` for demonstration purpose.

Is there a way to prevent the `remove` server method from being called, when the `files` state is being modified?

I would like to be able to programmatically remove the file from the Filepond UI, but do not want to actually remove it from the file storage.

**Comment by rikschennink** [comment]
I'm looking into it, I don't think it should call `remove`, not a 100% sure, will get back to you.

**Comment by rikschennink** [comment]
Just published FilePond `4.19.1` which should fix this problem.

Not sure if with all the other logic going on this venture will be successful (FilePond wasn't developed to be a view only solution) but I'm interested for the result.

**Comment by jacklimwenjie** [comment]
Crazy, thanks for the prompt reaction!
