### ISSUE TITLE
Drag reorder not working

### ISSUE THREAD

**Issue by dado3272** [pqina/react-filepond#147]
Hello, I'm facing an issue with react-filepond. With this package I can't use the drag reorder function in my react app, while it works on a plain html file with the standard filepond.

I noticed that the pointerdown event of the filepond-item-***** element is missing, so I think that it might be the problem

Thanks for your help

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently. 

The more information we have, the faster the issue can be resolved.

We will be able to more closely look at your issue once the issue template has been filled out. This issue will be closed in 5 days if the above is not addressed.

**Comment by dado3272** [comment]
**Describe the bug**
The drag reorder function in the react version of filepond doesn't work, while it works on a plain html file with the standard filepond.

It doesn't even work on the demo provided in the [README file](https://codesandbox.io/s/github/KimGenius/React-file-pond).

I noticed that the pointerdown event of the filepond-item-***** element is missing, so I think that it might be the problem

**To Reproduce**
Simply create a new react filepond project, even with the code provided by the examples

**Expected behavior**
The drag reorder is expected to work

**Information about your project:**
- Browser and the version: Firefox 79.0

- Operating system: Windows 10

- FilePond version 4.19.2

**Comment by rikschennink** [comment]
Need to add `allowReorder={true}`

I've updated the demo with the latest version of FilePond
