### ISSUE TITLE
Loading state

### ISSUE THREAD

**Issue by serendipity1004** [pqina/react-filepond#148]
I would like to be able to receive loading state of whether the file has been uploaded to the server or not as a prop. Would this be possible?

I am currently uploading file to S3 like below
```
server={{
                    process: async (fieldName:any, file:any, metadata:any, load:any, error:any, progress:any, abort:any, transfer:any, options:any) => {
                        try {
                            const name = getFullFileName(file.name);

                            const presigned = await S.jobPostService.uploadNameCardImage(file, name, (e) => {
                                progress(e.lengthComputable, e.loaded, e.total);
                            });

                            load('uploaded');
                        } catch (e) {
                            error('upload failed')
                        }
                        return {
                            abort: () => {
                                abort();
                            }
                        }
                    }
                }}
```

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently. 

The more information we have, the faster the issue can be resolved.

We will be able to more closely look at your issue once the issue template has been filled out. This issue will be closed in 5 days if the above is not addressed.
