### ISSUE TITLE
NPM Package seems to be missing features

### ISSUE THREAD

**Issue by WillemDuPlessis** [pqina/react-filepond#149]
Good morning

It seems that the latest [NuGet package (version 7.0.1)](https://www.npmjs.com/package/react-filepond) doesn't seem to contains some features included in the latest master build. It was last released 2 years ago and I was wondering if you could update it to contains the latest changes.

In particular it doesn't seem to contain the styling props as introduced in [this PR](https://github.com/pqina/filepond/pull/362).

If I am mistaken and it is up to date, could you please help me on how to use the styleButtonRemoveItemPosition property in React using TypeScript?

I get the error "Property 'styleButtonRemoveItemPosition' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<FilePond> & Readonly<FilePondProps> & Readonly<...>'" when trying to add the attribute to the FilePond component.

**Comment by rikschennink** [comment]
The react package has filepond as a peerDependency, so you can run `npm i filepond@latest` to install the latest version.

**Comment by WillemDuPlessis** [comment]
Thanks for the quick reply.

I have done so, but the react-filepond FilePond component still references the FilePondProps interface contained in the same file, and this only extends the FilePondDragDropProps,
    FilePondServerConfigProps,
    FilePondLabelProps,
    FilePondSvgIconProps,
    FilePondCallbackProps,
    FilePondHookProps &
    FilePondBaseProps interfaces, unlioke the FilePondOptions interface in the filepond package which extends FilePondDragDropProps,
    FilePondServerConfigProps,
    FilePondLabelProps,
    FilePondSvgIconProps,
    FilePondCallbackProps,
    FilePondHookProps,
    **FilePondStyleProps** &
    FilePondBaseProps

It seems the index.d.ts for react-filepond file's only imports are for  React itself, is this correct?

**Comment by WillemDuPlessis** [comment]
It seems my project was referencing @types/react-filepond which seems to be the outdated version. I will go raise an issue on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)
Thanks for your help!
