### ISSUE TITLE
acceptedFileTypes={['video/*']} doesn't work in safari

### ISSUE THREAD

**Issue by hadasmeitav** [pqina/react-filepond#152]
**Safari version : 13.1.1**

i'm using this library, which works fine in chrome, but not in safari.

**my issue is :** 
when i set `acceptedFileTypes={['video/*']}` 
 1. in chrome - it accepts all video types.
 2. in safari - it will only accept `mov` files, and not all video type files.

i've also tried explicit video types : 
when i set `acceptedFileTypes={['video/mp4']}` : it does the expected behaviour on both, and accepts only mp4 files.

i don't wish to set all possible video types, and would like to use the `video/*` filter.

I've registered the components like so : 
```
registerPlugin(FilePondPluginMediaPreview, FilePondPluginFileValidateType)
...
<FilePond
  ref={fileRef}
  files={files}
  allowMultiple={false}
  labelIdle={labelIdle}
  className="video"
  instantUpload={false}
  onupdatefiles={(items) => {
    setFiles(items)
  }}
  onremovefile={() => toggleDisplayProgress(false)}
  acceptedFileTypes={['video/*']}
  required
/>
```

here's what i see in safari when opening the upload on the web : 
![Screen Shot 2020-08-28 at 12 11 30 PM](https://user-images.githubusercontent.com/9152018/91946531-f8073f80-ed07-11ea-8a2d-5dca917ea296.png)

i can set the video types specifically [here][2] as described [in this ticket][1]

  [1]: https://stackoverflow.com/a/19323498
  [2]: https://trac.webkit.org/browser/trunk/Source/WebCore/platform/MIMETypeRegistry.cpp

**Comment by rikschennink** [comment]
https://stackoverflow.com/questions/63700557/filepond-doesnt-work-with-video-type-in-safari
