### ISSUE TITLE
How can I persist file state of uploaded files using react useState hooks? 

### ISSUE THREAD

**Issue by leonh** [pqina/react-filepond#154]
How can I persist file state of uploaded files using react useState hooks?  
I am using filepond with react and functional components with useState hooks to store the state of the files added to filepond based on the example of the readme in this project.

use case
In my app FilePond is part of a larger form split up into sections.  I require the filpond widget to be toggled depending on the state of my form. If I upload a file to my server filepond correctly shows upload complete however if I hide the filepond widget and redisplay filepond the file is re-uploaded. It's state as an complete uploaded file is getting lost somewhere. 

**To Reproduce**
https://codesandbox.io/s/react-filepond-forked-bntuq?file=/src/App.js

the checkbox will toggle the display of filepond. 1 upload a file 2 click checkbox to hide filepond, 3 click once more to show filepond  4 the file is then re-uploaded automatically

**Expected behavior**
An uploaded file would not automatically re-upload when the filepond widget is re-displayed. the upload state of the file should be stored fully in a call to use state hook "setFiles" on the parent component. how can this be achieved?

**Information about your project:**
- Your browser and the version: Chrome 86
- Your operating system:  MacOS 10

- FilePond version: latest released 

**Additional context**
I have a working endpoint on the server that can save and delete files from filepond. but this is not linked to the codesandbox

**Comment by rikschennink** [comment]
The FilePond files list needs to know if a file has already been uploaded, if it receives a file object it will push to it to the server. so syncing the files prop as a plain list of files won't work.
https://pqina.nl/filepond/docs/patterns/api/filepond-object/#setting-initial-files

**Comment by rikschennink** [comment]
Closed because inactive

**Comment by chriswait** [comment]
Hi @rikschennink

Do you have any examples of how the files prop can be used to preserve existing file state between unmounting/mounting without triggering any reuploads or fetches?

I have tried using it as described in the [Files](https://pqina.nl/filepond/docs/api/instance/properties/#files) section of the Filepond documentation.

However, these approaches seem to trigger requests to the `restore` or `load` endpoints which are unnecessary given the file data is already available in our useState.

Happy to open a fresh issue if more appropriate, forked codepen [here](https://codesandbox.io/p/sandbox/react-filepond-live-demo-forked-r6mrsk)

**Comment by rikschennink** [comment]
@chriswait I think if you set the `mock` information it doesn't restore the file. Not a 100% sure.
