### ISSUE TITLE
Calles onupdatefiles on initial render

### ISSUE THREAD

**Issue by Tjerk-Haaye-Henricus** [pqina/react-filepond#156]
**Reproduce**
Render Filepond with files propertiy set.

**Current Behavior**
If filepond was rendered with files it initially calles the onupdatefiles handler

**Better behavior**
Do only call onupdatefiles when files are updated :)

**Comment by Tjerk-Haaye-Henricus** [comment]
Any update on this ?

**Comment by rikschennink** [comment]
FilePond will call `onupdatefiles` everytime the internal file list changes, this also happens when rendering FilePond so therefor it calls `onupdatefiles`.

**Comment by Tjerk-Haaye-Henricus** [comment]
Hoi, thanks for repliing :) 

Can i determine if its the same file as before with some other flags ?

**Comment by rikschennink** [comment]
could set metadata

**Comment by meszaros-lajos-gyorgy** [comment]
Hi! I have something similar happening for `onprocessfiles`, which is getting called 5-10 times after uploading a single file.

**Comment by rikschennink** [comment]
Closed because inactive
