### ISSUE TITLE
Allow us to keep filepond instances

### ISSUE THREAD

**Issue by nt4f04uNd** [pqina/react-filepond#158]
**Is your feature request related to a problem? Please describe.**
Now the `FilePond` component creates its own filepond instance and destroys it after unmount.

**Describe the solution you'd like**
Component shouldn't destroy old instances, rather track them as a map, or at least, allow to do that.

**Additional context**
I need this because I want to allow users have multiple drafts that are opened with modals, and I want to allow them modify them, then close, modify another one blah blah blah and eventually to press the "upload all" button or something like that. Now I can't do this because filepond intances lifecycle isn't much manageable for me.

**Comment by rikschennink** [comment]
Hi, In that situation I'd advise to use the vanilla version of FilePond instead of the React adapter.

**Comment by nt4f04uNd** [comment]
Yeah ok. By the way, maybe this is too verbose and irrelevant for this library and should be closed? What do you think?

**Comment by rikschennink** [comment]
I'm currently not planning to add something like this because I feel it's better to shield access to the instance.

I'm happy to re-open the issue if more developers chime in.
