### ISSUE TITLE
Server Example with Redux

### ISSUE THREAD

**Issue by pkhodaveissi** [pqina/react-filepond#16]
Hi, congratulations on creating this great project,

I was wondering if there is an example of Filepond where redux is responsible for managing data and process/revert requests, 

I have this server where I need to upload my file with additional request body parameters (which I haven't tried yet) and Authorization Header info(which is not a problem based on docs and what I experienced)

thank you for your time

**Comment by rikschennink** [comment]
I haven't tried this yet, but I do have some experience with Redux and I would think that setting up custom server functions and dispatching actions from inside those functions should work.

**Comment by pkhodaveissi** [comment]
I was in a rush so I couldn't stop trying that but If went back to refactor, I'll try and let you know, you can close this, but I would like to add an example for later reference
