### ISSUE TITLE
React FilePond file size validation

### ISSUE THREAD

**Issue by dineshtalekar777** [pqina/react-filepond#168]
I am using the react file pond in spfx solution I want to validate the file size to max 10 MB. Could you please some one help with live example in codesandbox.

I am trying to use file size validation plugin. But it is not working.

Below is the code snap attached it is giving the an error at maxFileSize

![image](https://user-images.githubusercontent.com/13659423/106350257-442bcf80-62fa-11eb-8be0-8fceb20aa5eb.png)

![image](https://user-images.githubusercontent.com/13659423/106350335-ccaa7000-62fa-11eb-8b64-974c9bba6eaa.png)

**Comment by rikschennink** [comment]
Are the types loaded correctly?

Maybe set it as `maxFileSize="10MB"`?

**Comment by dineshtalekar777** [comment]
@rikschennink - How to load the types

**Comment by rikschennink** [comment]
@dineshtalekar777 They should load automatically. Not sure why they're not loading.  I think you can temporarily add `// @ts-ignore` before the prop to ignore the warning.

**Comment by rikschennink** [comment]
Just updated all plugin type declarations, should be fixed now.
