### ISSUE TITLE
Sometimes onupdatefiles function is getting called before beforeAddFile in React

### ISSUE THREAD

**Issue by dineshtalekar777** [pqina/react-filepond#169]
Hi All,

Sometimes onupdatefiles function is getting called before beforeAddFile this function calling in React JS

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently. 

The more information we have, the faster the issue can be resolved.

We will be able to more closely look at your issue once the issue template has been filled out. The issue will be closed until the above is addressed. 

**Please leave a comment after you've updated the issue.**
