### ISSUE TITLE
A couple Questions.

### ISSUE THREAD

**Issue by chobo2** [pqina/react-filepond#17]
Hi

I am looking into use this plugin (from the examples it looks pretty sweet).

I am wondering though 

1. Is there a property to change the  label? Right now "Drag & Drop your picture or Browse" I would like to change it to like ".... or Click Here to Add Files"

2.  I have a form and I would like to submit the images on form submit, can this easily be done. You can think of something like craiglists where someone creates a new post, they add some information and their pictures and then hit the "submit" button.

3. Possible to add custom borders around image preview? Like how craiglist adds to first picture that it is featured. If you drag a different image to first position it changes that new images to the "featured" border.

4. Get count of how many images where added to filepond? If they drag 3 images in. I want to update a counter outside of filepond with that count.

**Comment by rikschennink** [comment]
Thanks!

1. Yes, all labels can be edited, see docs for more info on this.

2. This is possible using the file-encode plugin. If this concerns big files I would advise against it as too much encoded data often causes mobile browsers to crash when the page is submitted. It's best to immediately upload when the file is dropped and only submit the unique file ID.

3. This should be possible with some CSS tweaks, you could also have a separate pond for the featured image.

4. Yes, you can track the number of files in FilePond, subscribe to `onadditem` and in the callback simply request all items.

**Comment by rikschennink** [comment]
> When you say big files what are you considering big files? Also does amount of images being put in a "pond" affect it? Also if I would just submit the unique file Id (not sure if I would generate this id through file pond?), how would I handle the situation were they made a mistake and uploaded the wrong file and decided to remove it.

Output bigger than say 100 Kb could already cause trouble, file encoding in my experience is only useful if you're either A. only use the application on desktop or B. upload client-side resized and compressed profile pictures.

> I see that a unique id has to be generated from the server. I still have to do more reading on this.

Some kind of unique file `id` needs to be returned, this could also be a path or filename, as long as it's unique. FilePond will store the `id` and will pass it to the server when a file is for instance removed, or the parent form is submitted, the `id` then allows you to identify the file on the server.

> I see that the files are done async but I am getting a problem and I am not sure if it filepond that is timing out? If I drag 8 images they will all upload fine, if I drag like 30 files in like 20 of them will fail.

What exact error is thrown? And do you have public test case that I can take a look at?

> Is there something built in to clear successful uploaded files after X seconds?

You can add some kind of timeout in the `onprocessfile` callback

> How do I set options in React?

See https://pqina.nl/filepond/docs/patterns/frameworks/react/

**Comment by chobo2** [comment]
@rikschennink 

> > When you say big files what are you considering big files? Also does amount of images being put in a "pond" affect it? Also if I would just submit the unique file Id (not sure if I would generate this id through file pond?), how would I handle the situation were they made a mistake and uploaded the wrong file and decided to remove it.
> 
> Output bigger than say 100 Kb could already cause trouble, file encoding in my experience is only useful if you're either A. only use the application on desktop or B. upload client-side resized and compressed profile pictures.

Ok, I will try to avoid this then. 

> 
> > I see that a unique id has to be generated from the server. I still have to do more reading on this.
> 
> Some kind of unique file `id` needs to be returned, this could also be a path or filename, as long as it's unique. FilePond will store the `id` and will pass it to the server when a file is for instance removed, or the parent form is submitted, the `id` then allows you to identify the file on the server.
> 

On this note, Is there away to disable allowing an image to be removed? If I go my "reset" way, I don't think it will make sense to have the X button still shown.

> > I see that the files are done async but I am getting a problem and I am not sure if it filepond that is timing out? If I drag 8 images they will all upload fine, if I drag like 30 files in like 20 of them will fail.
> 
> What exact error is thrown? And do you have public test case that I can take a look at?

it seems to have something to do with the timeout. When I put the time out like 10000000 alll would pass. I have to retry again to see if their was an error but I believe the ajax call just got cancelled.

> 
> > Is there something built in to clear successful uploaded files after X seconds?
> 
> You can add some kind of timeout in the `onprocessfile` callback
> 

I see this takes in a file but I don't see any property on it that would just clear it from the ui, can you elaborate on this more.

> > How do I set options in React?
> 
> See https://pqina.nl/filepond/docs/patterns/frameworks/react/


Thanks

**Comment by rikschennink** [comment]
> If I go my "reset" way

I'm not sure what you mean by that :-)

> it seems to have something to do with the timeout. When I put the time out like 10000000 alll would pass. I have to retry again to see if their was an error but I believe the ajax call just got cancelled.

Thanks for clarifying I'll investigate this further.

> I see this takes in a file but I don't see any property on it that would just clear it from the ui, can you elaborate on this more.

It returns a file item, the file item can then be removed using the `pond.remove` method.

> How do I send something extra when uploading an Image. I need to pass the userId so I can link the uploaded image to the right user.

You can add `metadata` to a file object using the `setMetadata` method and the `metadata` property in the `addfile` method. The metadata is then accessible in the custom `process` function or sent to the server with the same field name when using the default processing method.

**Comment by chobo2** [comment]
> > If I go my "reset" way
> 
> I'm not sure what you mean by that :-)
> 
I mean if I remove the images after say 5 seconds, I am not sure if there is any need to have the X be shown on each image?

> > it seems to have something to do with the timeout. When I put the time out like 10000000 alll would pass. I have to retry again to see if their was an error but I believe the ajax call just got cancelled.
> 
> Thanks for clarifying I'll investigate this further.
> 
no problem, on this not is there a recommended max of images that can be dragged into filepond at any given time? Without preview of the image.

With the timeout issue, it does not seem to be like be a count issue alone but maybe size and count. I just made 208 pics that are around 171kb each for a total of 36mbs  and without a huge timeout most of them get cancelled.

> > I see this takes in a file but I don't see any property on it that would just clear it from the ui, can you elaborate on this more.
> 
> It returns a file item, the file item can then be removed using the `pond.remove` method.
> 
> > How do I send something extra when uploading an Image. I need to pass the userId so I can link the uploaded image to the right user.
> 
> You can add `metadata` to a file object using the `setMetadata` method and the `metadata` property in the `addfile` method. The metadata is then accessible in the custom `process` function or sent to the server with the same field name when using the default processing method.

Could you give an example of how this would work?  I am not following

**Comment by rikschennink** [comment]
> I mean if I remove the images after say 5 seconds, I am not sure if there is any need to have the X be shown on each image?

True, you could hide it with CSS if you wish, there's currently no option to disable it otherwise.

> no problem, on that note, is there a recommended max of images that can be dragged into filepond at any given time (none preview mode). It seems like it could handle alot but I think the animations can hammer it down.

Eventually animations will hammer it down, haven't tested but it can deal with a lot of files before it gets too crazy. Might optimize this further in the future.

> With the timeout issue, it does not seem to be like be a count issue alone but maybe size and count. I just made 208 pics that are around 171kb each for a total of 36mbs and without a huge timeout most of them get cancelled.

Fixing the timeout situation now. Should be a new version online tomorrow morning.

> Could you give an example of how this would work? I am not following

```js
file.setMetadata('userId', 'foo');

file.getMetadata('userId'); // will return 'foo'
```

**Comment by chobo2** [comment]
> > I mean if I remove the images after say 5 seconds, I am not sure if there is any need to have the X be shown on each image?
> 
> True, you could hide it with CSS if you wish, there's currently no option to disable it otherwise.
> 
> > no problem, on that note, is there a recommended max of images that can be dragged into filepond at any given time (none preview mode). It seems like it could handle alot but I think the animations can hammer it down.
> 

> Eventually animations will hammer it down, haven't tested but it can deal with a lot of files before it gets too crazy. Might optimize this further in the future.
> 

Is there a way to disable the animations?  I think after like 100 the animations look slow. I just know I am going to have to support 500 files to be dragged at one time as that is what a competitors site can handle with their photo plugin.

> > With the timeout issue, it does not seem to be like be a count issue alone but maybe size and count. I just made 208 pics that are around 171kb each for a total of 36mbs and without a huge timeout most of them get cancelled.
> 
> Fixing the timeout situation now. Should be a new version online tomorrow morning.
> 
> > Could you give an example of how this would work? I am not following
> 
> ```js
> file.setMetadata('userId', 'foo');
> 
> file.getMetadata('userId'); // will return 'foo'
> ```

How do I do this in react though? I don't have a file object.

**Comment by rikschennink** [comment]
By the way, version `3.0.1` should fix the timeout situation.

**Comment by chobo2** [comment]
> > Is there a way to disable the animations? I think after like 100 the animations look slow. I just know I am going to have to support 500 files to be dragged at one time as that is what a competitors site can handle with their photo plugin.
> 
> Holy moly batman, 500 files, that's a crazy amount. How are these files added? With a folder, or are they all selected in one go? I'm thinking it might be better to add some sort of `batch` mode, so files need to cleaned-up first before continuing with new files.
> 

Well, what I noticed(and this does not seem to be only a filepond issue, so wondering if it is a drag limit by folder) is if you drag a folder in it will cap the count at 100. 

If I go into the folder and highlight all 500 in the folder and drag them in then it passes the 100 limit.

This the plugin that a compeitor is using, https://www.filestack.com/

I can't evaluate it totally on the competitors site but it will allow you drag 500 images in at a time, they are all in a staged mode and then they have a "upload all button", so I don't know well it handles it once you click "upload" (if it does it in batches at this point or all at the same time).

I think a batch mode would be good, I think the bigger issue is not that all images have to upload all at the same time, more to allow you to drag in alot and have them in a queue mode so you can sort of walk away and let it do it's thing.

> > How do I do this in react though? I don't have a file object.
> 
> The file item object is returned in almost all callback methods, and you can manually request the file item object using the `getItem` method (see docs).

hmm, still not following 100%, I going to have to play around with this. So I have to get in the middle of the post request to add the "userId" to each file?

**Comment by rikschennink** [comment]
I'll add it to the list of features. For the near term future, FilePond is not the goto solution for uploading that much files in one go.

> hmm, still not following 100%, I going to have to play around with this. So I have to get in the middle of the post request to add the "userId" to each file?

No, you add them when the file is added to the list. You can see how a callback can be set up in the example on this page, callback parameters can be found in the FilePond instance docs. 
https://pqina.nl/filepond/docs/patterns/frameworks/react/

**Comment by chobo2** [comment]
Cool, I will check it out though unfortunately a chance I won't be going with filepond as I need something that can handle lots of files uploaded.

I am wondering do you know of any good libraries that can bulk upload?

**Comment by rikschennink** [comment]
To be honest, I'm not sure, I think it'll have to be something that groups them as a single upload indicator as updating 500+ DOM nodes is going to be taxing on the CPU no matter which upload tool you use. 

I'll close the issue.

**Comment by developdeez** [comment]
Where can I find documentation on how to change the label text for things like "Uploading..."?
Didnt see in the docs?

**Comment by rikschennink** [comment]
@developdeez https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#labels

**Comment by SbrTa** [comment]
I am thinking of using filepond in my project. But i can't find a way to allow only images. How can i achieve that?
