### ISSUE TITLE
Property setOptions doesn't exists on filepond-plugin-file-metadata 

### ISSUE THREAD

**Issue by ravivarma-dot** [pqina/react-filepond#170]
Hi,

I'm using filepond and wanted to add some metadata to files. I installed filepond-plugin-file-metadata and followed filepond documentation but its throwing error saying setOptions doesn't exists. Please see attached image for error.

Below is the documentation I followed.
https://pqina.nl/filepond/docs/patterns/plugins/file-metadata/#usage

Thanks, Filepond is a great library.

![image](https://user-images.githubusercontent.com/64154058/109445066-b9c7b000-7a0c-11eb-8047-8230a9377c16.png)

**Comment by rikschennink** [comment]
The React doesn't export the `setOptions` method.

You can use it like this
```jsx
<FilePond fileMetadataObject={{ 'hello': 'world' }}/>
```
