### ISSUE TITLE
Uploading multiple files works but doesn't show percentage or change to complete once done

### ISSUE THREAD

**Issue by lucvanrooyen** [pqina/react-filepond#171]
**Describe the bug**
Hi there - when uploading multiple files I am having a weird  behaviour - the first 1/2 files show the upload percentage and once complete it changes to Complete but the rest just show uploading even once the file has uploaded successfully 

**Logs**
N/A

**To reproduce**
Upload multiple files - in my case its 9

**Expected behavior**
Shows progress percentage and changes to complete once done

**Information about your project:**
- Your browser and the version: Chrome Version 88.0.4324.192

- Your operating system: All OS

- FilePond version : Latest
<img width="198" alt="Screenshot 2021-03-03 at 09 28 14" src="https://user-images.githubusercontent.com/53639180/109769856-75523500-7c03-11eb-8beb-bf89cc504314.png">

**Comment by rikschennink** [comment]
Hi, please supply an online test case, happy to take a look.

**Comment by lucvanrooyen** [comment]
Client policy is blocking me from exposing some of our code - would a screen recording and network snap shot suffice?

**Comment by rikschennink** [comment]
You can fork this code sandbox https://codesandbox.io/s/react-filepond-live-demo-iw9ri and create a mock process method.

**Comment by lucvanrooyen** [comment]
https://codesandbox.io/s/react-filepond-live-demo-forked-gjsil?file=/src/index.tsx

**Comment by lucvanrooyen** [comment]
We have also noticed that on single file uploads that usually show the percentage - if the file is large it also does not show the percentage - it just shows "uploading"

**Comment by rikschennink** [comment]
I just tried to take a look but the server prop is set to an empty string.

**Comment by lucvanrooyen** [comment]
I cant give you our servers details? Can you not replace it with your own server? Is there anyway we could have a video call?

**Comment by lucvanrooyen** [comment]
We are using an azure cloud blob

**Comment by rikschennink** [comment]
@lucvanrooyen This is an open source MIT licensed product, so no, I can't hop on a call.

**Comment by serojatech** [comment]
> 

I have the same issue on production server. 
Percentage progress shows on local development but not showing on production server.
