### ISSUE TITLE
filepond within a tabs component (removefile event being trigered)

### ISSUE THREAD

**Issue by PedroRTomas** [pqina/react-filepond#172]
Hello,
I've been working on a vue project where I need to have a tabs-component. Within each tab, I need to have a filepond component. (For each tab, the user needs to be able to submit files)
What is happening: While changing tabs, the removefile event is being fired and files are being wrongly deleted.

What I think it's happening: While changing between tabs, the instance of filepond is being deleted and a new one is being created (with different references). As a result, filepond is emitting removefile event because the instance with a specified reference has been actually deleted, but the main component is still there.

I've tried to take advantage of any information passed to the callback specified for '@removefile', however, the first parameter seems always to be null and the second one is always equal (For each tab).

Now, any idea how I can face this? Perhaps if I could differentiate the event of clicking on 'x' for deleting the file, from simpling removing the component from DOM (while changing tab), that would do, but I don't know how to make that difference.

Thanks in advance!

**Comment by rikschennink** [comment]
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently.

The more information we have, the faster the issue can be resolved.

We will be able to more closely look at your issue once the issue template has been filled out. The issue will be closed until the above is addressed.

**Please leave a comment after you've updated the issue.**
