### ISSUE TITLE
The prompt that the file exceeds the maximum limit is gone

### ISSUE THREAD

**Issue by wangshangkun** [pqina/react-filepond#173]
**Describe the bug**
The prompt that the file exceeds the maximum limit is gone

When I use the compact circle layout, then selected file exceeds the maximum limit, but the prompt is gone, only a close button is left。

How can I solve this problem?

**Comment by rikschennink** [comment]
The circle layout isn't very suitable to show those errors, I advise to catch the error with error event callback and then show an error next or above the field.
