### ISSUE TITLE
Clicking on “Tap to cancel” is not working in some cases

### ISSUE THREAD

**Issue by mehimanshupatil** [pqina/react-filepond#183]
When implementing custom server object. If promise is returned the "tap to cancel" doesn't work  while uploading File.
```
 server={{
              process: async(
                fieldName,
                file,
                metadata,
                load,
                error,
                progress,
                abort
              ) => {
                 // code
                return {
                  abort: () => { 
                    console.log(`aborts`);
                    abort();
                  },
                };
               },
            }}
```
In above example if async keyword is added to process function the returned abort function is not called 

[check codesandbox](https://codesandbox.io/s/filepond-remove-issue-o0dzq?file=/src/App.js)

possible fixes: 
strict type checking

**Comment by rikschennink** [comment]
The server.process property doesn’t accept promises so this won’t work.

Will close because issue doesn’t conform to issue template.
