### ISSUE TITLE
Missing option to set the locale

### ISSUE THREAD

**Issue by antipopp** [pqina/react-filepond#187]
**Is your feature request related to a problem? Please describe.**
An option that would set the locale imported

**Describe the solution you'd like**
Maybe just a prop that ideally would take a string as the locale (it_IT or en_US)
`<FilePond
    files={files}
    onupdatefiles={setFiles}
    allowMultiple={true}
    maxFiles={10}
    name="files"
    locale="it_IT"
/>`

**Comment by rikschennink** [comment]
You can spread the object.

```jsx
<FilePond {...it_IT} files={files}/>
```

**Comment by antipopp** [comment]
oh I see. Is there any other way to change locale? I'd like to do it programmatically as I'm using i18next to handle localization. I came up with a 'useEffect' to handle the change, but I was wondering if there was a prettier way (I'm going definitely OT, close the issue if you want):

```js
const [filepondLocale, setFilepondLocale] = useState({})
const { t } = useTranslation()

useEffect(() => {
         switch (window.localStorage.getItem('lang')) {
            case 'it':
                setFilepondLocale(it_IT)
                return
            default:
                setFilepondLocale({})
                return
        }
}, [t]}
```

**Comment by rikschennink** [comment]
I don't think that's currently possible, you'd have to destroy and re-create the component.
