### ISSUE TITLE
Best practice to use Filepond on a React Server Side Rendering technology web site.

### ISSUE THREAD

**Issue by jerome-diver** [pqina/react-filepond#189]
Hello and thank you for your library.
Is it possible (without the need to write all the events) to use Filepond with a React SSR web site ?
For example, to get file show on the client side, but not upload on server side after to add the file/image (innside a form with any other inputs) , and to upload it at form submit (so not only the form for this uploaded things, but full content of data, including the file).
Or is it not the best library to use that on SSR web site ?

**Comment by rikschennink** [comment]
It can be used with SSR but it'll just wait till the client loads and then it'll populate the files.

I'll close the issue because it doesn't conform to the issue template.

**Comment by jerome-diver** [comment]
ok, thank you for your answser.
The idea to use it with SSR is not to post a request everytime something is changing on a form view client side... it is not logic with SSR concept.
If you would like one day to implement something for SSR, let me know please. Your library is nice (i will sure use it with SSR when it will be possible).

**Comment by rikschennink** [comment]
You could use mock files, see here: https://pqina.nl/filepond/docs/api/instance/properties/#files

**Comment by jerome-diver** [comment]
yes, i see and tested this already, but it is to much. Need to implement a function to call to get and add mocked data... i'm searching for something more "efficient" (it is not the best adjective i think, but Englmish is not my language, i don't know which adjective to use to describe it as i hope it to be more...).
Anyway, i will find or do myslef one.
