### ISSUE TITLE
Progress indicator SVG is not centered vertically

### ISSUE THREAD

**Issue by raRaRa** [pqina/react-filepond#19]
### Summary
The progress indicator SVG is not vertically centered.
<img src="https://i.imgur.com/GXQFlwd.png"/>

The div parent of the progress indicator seems to be positioned correctly in the center, but the SVG child is not.

The SVG has the following styles:
```
.filepond--progress-indicator svg {
    width: 100%;
    height: 100%;
    transform-box: fill-box;
}
```

And when I remove the height, it fixes the issue.

Any ideas why this could be a problem, is it just for me?

### How to reproduce
Upload any file.

### Expected behaviour
The SVG should be vertically centered.

### Additional information

| Environment  | Version
|------------- | -----------
| OS           | Windows 10
| Browser      | Chrome 69

**Comment by raRaRa** [comment]
Seems to be an issue on my end, I had a global style which had the following:

```
    vertical-align: middle;
```

Sorry about this!

**Comment by raRaRa** [comment]
For those who use bootstrap, simply add this style to fix the problem. 

```
.filepond--wrapper svg {
    vertical-align: unset;
}
```

**Comment by rikschennink** [comment]
Thanks @raRaRa!

I'll put the `vertical-align` in the default style so it automatically works on Bootstrap as well.
