### ISSUE TITLE
Filepond automatically URI encodes S3 signed URL - causing a 400 Error

### ISSUE THREAD

**Issue by davidli3100** [pqina/react-filepond#192]
Pretty simple issue:

The `X-Amz-Credentials` query string param starts as  `STRING/20210903/ca-central-1/s3/aws4_request`  but after filepond gets the file, that query string gets encoded to  `STRING%2F20210903%2Fca-central-1%2Fs3%2Faws4_request` which breaks S3 authentication.

Is there a way to override encoding or maybe decode the URI before filepond sends the request?

**Comment by rikschennink** [comment]
https://github.com/pqina/filepond/issues/610#issuecomment-733046306

Will close because the issue does not follow the issue template and can be resolved with custom `server` function, see docs referenced in linked comment.
