### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by andrewkazan** [pqina/react-filepond#196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated React FilePond, FilePond, and all plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

If you use TypeScript, you has error that FilePondReact does not exist default FilePond properties
![Screenshot 2021-10-29 at 11 27 49 AM](https://user-images.githubusercontent.com/31125066/139402745-fc4e2fb2-1c32-424d-ba7c-08305ecd4876.png)

### Reproduction

Use Ract FilePond, use TypeScript, use default FilePond properties, got Error

### Environment

```markdown
- Device: Macbook pro 2019 i9
- OS:Big Sur
- Broser:Chrome
- React version:17
```

**Comment by rikschennink** [comment]
I don't think `dataMaxFileSize` is a valid prop, will close for now.

**Comment by andrewkazan** [comment]
This is issue is not about dataMaxFileSize. This about "credits" prop
