### ISSUE TITLE
FilePond - Issue when component is unmounted

### ISSUE THREAD

**Issue by svaldi** [pqina/react-filepond#2]
Hello, 

I'm testing the React Component and something caught my attention, while I was unmounting a component where the File Pond component has been mounted before it throws an error: 

```
Uncaught TypeError: Cannot read property 'restoreElement' of undefined
    at destroy (filepond.js:7904)
    at filepond.js:1957
    at Array.forEach (<anonymous>)
    at filepond.js:1956
```

```
// destroys apps and removes them from the app array
  var destroy = function destroy(hook) {
    // returns true if the app was destroyed successfully
    var indexToRemove = state.apps.findIndex(function(app) {
      return app.isAttachedTo(hook);
    });
    if (
      function(indexToRemove) {
        return 0;
      }
    ) {
      // remove from apps
      var app = state.apps.splice(indexToRemove, 1)[0];

      // restore original dom element
Line: 7904      app.restoreElement();

      return true;
    }

    return false;
  };

```

Tested on: 

> Google Chrome
> Version 65.0.3325.162 (Official Build) (64-bit)

Your component is great!!

**Comment by rikschennink** [comment]
@svaldi Thanks for reporting! I've reproduced the issue, hope to push a fix tomorrow.

**Comment by rikschennink** [comment]
@svaldi Just pushed version 1.2.0 of the React component to npm, and pushed version 1.2.1 of FilePond to npm. Getting the latest version should fix the problem.

**Comment by rikschennink** [comment]
I will close for now.
