### ISSUE TITLE
Preview Dimensions {width, height}

### ISSUE THREAD

**Issue by pkhodaveissi** [pqina/react-filepond#20]
Couldn't find documentation on passing dimension props to _filepond-plugin-image-preview_ while using react, would you mind giving me a hint on this?

thank you

**Comment by rikschennink** [comment]
Hi! It can be done in the same way as setting the core FilePond properties.

```jsx
<FilePond ref={ref => this.pond = ref}
    allowMultiple={true}
    imagePreviewMinHeight={44}
    imagePreviewMaxHeight={256}
    maxFiles={3}
    server="/api">
</FilePond>
```

**Comment by pkhodaveissi** [comment]
sure did, let me try and get back to you

**Comment by pkhodaveissi** [comment]
My Setup:

```
import FilePondImagePreview from "filepond-plugin-image-preview";
import FilePondTypeValidate from "filepond-plugin-file-validate-type";
import FilePondPluginFilePoster from "filepond-plugin-file-poster";
```
...

```
registerPlugin(
  FilePondImagePreview,
  FilePondTypeValidate,
  FilePondPluginFilePoster
);```

...

```
<FilePond
          imagePreviewMaxHeight={100} // or ="100" neither works
          ref={ref => (this.pond = ref)}
          acceptedFileTypes="image/jpeg, image/png"
          allowMultiple={this.props.allowMultiple ? true: false}
          oninit={() => this.handleInit()}
          onremovefile={(item)=> this.handleRemove(item)}
          labelIdle={`Drag & Drop your image or <span class="filepond--label-action">Browse</span>`}
          maxFiles={this.props.maxFiles}
          server={uploadServer}
        />
```

**Comment by rikschennink** [comment]
The image preview panel height gets above 100 pixels?

Can you remove the poster plugin and see if that makes a difference?

**Comment by pkhodaveissi** [comment]
sure will, but I gotta run now, i'll get back to you dear
