### ISSUE TITLE
[Bug] Typescript error on latest react version

### ISSUE THREAD

**Issue by Rocinante89** [pqina/react-filepond#212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated React FilePond, FilePond, and all plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

I'm getting the following typescript errors when trying to use filepond in a remix typescript application: 

`JSX element class does not support attributes because it does not have a 'props' property.`

`'FilePond' cannot be used as a JSX component.
  Its instance type 'FilePond' is not a valid JSX element.
    Type 'FilePond' is missing the following properties from type 'ElementClass': render, context, setState, forceUpdate, and 3 more.`

### Reproduction

Have a working repro here: https://codesandbox.io/s/vigilant-beaver-0or7bu?file=/app/routes/index.tsx

### Environment

```markdown
- Device: Macbook pro
- OS:latest
- Browser: chrome
- React version: 18.1.0
```

**Comment by rikschennink** [comment]
You're importing the vanilla JavaScript library instead of the React component.

**Comment by Rocinante89** [comment]
🤦‍♂️
