### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by AJKossi** [pqina/react-filepond#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated React FilePond, FilePond, and all plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

We are using filepond in nextjs project. 
Every file contains all other files. If we submit 2 files. Every file contains 2 files.
And when uploading to server, it becomes 4 files.
With one file, there is no bug. But from 2 we have this issue.

### Reproduction

![step1](https://user-images.githubusercontent.com/15309217/200378711-20342387-b7a5-4dac-bfa2-4cb864ef8700.PNG)
![server-response1](https://user-images.githubusercontent.com/15309217/200378856-2952a576-38e8-4012-8a7a-8ff23e07ccc1.PNG)
![step2](https://user-images.githubusercontent.com/15309217/200378781-e47c0b95-e67b-4e42-90b9-fb144ddbe17e.PNG)
![server-response2](https://user-images.githubusercontent.com/15309217/200378949-f16dddb3-0146-479d-987d-a212fd0d1fd6.PNG)

### Environment

```markdown
- Device:hp
- OS:windows
- Broser:firefox
- React version:17.0.2
```

**Comment by rikschennink** [comment]
Without a reproduction on codesandox I can't help with this, the issue description is just too vague.
