### ISSUE TITLE
[Bug] acceptedFileTypes doesn't appear to work at all

### ISSUE THREAD

**Issue by Jamesking56** [pqina/react-filepond#229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated React FilePond, FilePond, and all plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

The prop `acceptedFileTypes` appears to do nothing, my file uploader still shows all files rather than only the accepted ones and I'm able to upload any file.

### Reproduction

I updated the demo sandbox to show this, only accepting videos for example:

[![Edit react-filepond-live-demo (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-filepond-live-demo-forked-0oc641?fontsize=14&hidenavigation=1&theme=dark)

### Environment

```markdown
- Device: Desktop PC
- OS: PopOS! 22.04
- Browser: Brave Version 1.47.171 Chromium: 109.0.5414.87 (Official Build) (64-bit)
- React version: 17.0.2
```

**Comment by rikschennink** [comment]
You haven't loaded the file type validation plugin.

https://pqina.nl/filepond/docs/api/plugins/file-validate-type/
