### ISSUE TITLE
How to listen to event

### ISSUE THREAD

**Issue by paschaldev** [pqina/react-filepond#24]
Hello, firstly thanks for this package.

I have no Idea how to listen to events and attach an handler to it with React / Next.js. The documentation on React is brief. 

Are there callbacks? If yes, how do we use it? 

I tried using a ref and attaching the handler in `componentDidMount` but I got an error 

```js
this.pond.on is not a function
```

### component.js summary

```js
constructor(props)
{
        this.pond = React.createRef()
}

componentDidMount(){

        require('filepond-polyfill')

        this.pond.on('addfile', () => {

            console.log("File added")
        })
}

render(){
<FilePond 
        allowMultiple={false} 
        maxFiles={1} 
        server={config.media_upload_node} 
        name="file" 
        acceptedFileTypes={['image/*']} 
        ref={this.pond}
>
        {files.map(file => (
                <File key={file} src={file} />
        ))}
                                                                        
</FilePond>
}
```

**Comment by paschaldev** [comment]
Closing this, found the callback methods.

**Comment by rikschennink** [comment]
👍

For future reference.

It's basically all [these callbacks](https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#callbakcs) and they can be attached like shown below.

```jsx
<FilePond oninit={() => { ... }}></FilePond>
```
