### ISSUE TITLE
[Bug] can't get metadata in server api

### ISSUE THREAD

**Issue by zshnb** [pqina/react-filepond#242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you updated React FilePond, FilePond, and all plugins?

- [X] I have updated FilePond and its plugins

### Describe the bug

this is what I use in my project
```
const FileUploadButton = ({
  className,
  onFinishParse,
}: FileUploadButtonProps) => {
  registerPlugin(FilePondPluginFileValidateType)
  registerPlugin(FilePondPluginFileMetadata)
  return (
    <FilePond
      server={{
        process: '/api/upload',
        fetch: null,
        revert: null,
      }}
      allowFileMetadata={true}
      allowMultiple={true}
      maxParallelUploads={1}
      acceptedFileTypes={['application/pdf']}
      labelIdle="拖拽或点击上传文件"
      className={className}
      labelFileProcessingComplete="上传完毕"
      labelFileProcessing="上传中"
      onprocessfiles={() => {
        console.log('process files')
      }}
      onprocessfilestart={(file) => {
        console.log(`file ${file.filename} process start`)
      }}
      onprocessfile={(error, file) => {
        if (!error) {
          console.log(`file ${file.filename} process finished`)
        }
      }}
    />
  )
}

export default FileUploadButton

```

how ever, I checked request body, there is no json
<img width="533" alt="image" src="https://github.com/pqina/react-filepond/assets/17894980/6806886a-46e8-4069-9ae0-1ac11c3fc52b">
how can I get default file metadata in server?

### Reproduction

```
const FileUploadButton = ({
  className,
  onFinishParse,
}: FileUploadButtonProps) => {
  registerPlugin(FilePondPluginFileValidateType)
  registerPlugin(FilePondPluginFileMetadata)
  return (
    <FilePond
      server={{
        process: '/api/upload',
        fetch: null,
        revert: null,
      }}
      allowFileMetadata={true}
      allowMultiple={true}
      maxParallelUploads={1}
      acceptedFileTypes={['application/pdf']}
      labelIdle="拖拽或点击上传文件"
      className={className}
      labelFileProcessingComplete="上传完毕"
      labelFileProcessing="上传中"
      onprocessfiles={() => {
        console.log('process files')
      }}
      onprocessfilestart={(file) => {
        console.log(`file ${file.filename} process start`)
      }}
      onprocessfile={(error, file) => {
        if (!error) {
          console.log(`file ${file.filename} process finished`)
        }
      }}
    />
  )
}

export default FileUploadButton

```

### Environment

```markdown
- Device: Mac
- OS: Mac
- Broser: Chrome
- React version: 18
```

**Comment by rikschennink** [comment]
With PHP you can get the metadata with `$_POST['filepond']` and the file with `$_FILES['filepond']`, see: https://pqina.nl/filepond/docs/api/server/#process

**Comment by zshnb** [comment]
> With PHP you can get the metadata with `$_POST['filepond']` and the file with `$_FILES['filepond']`, see: https://pqina.nl/filepond/docs/api/server/#process

but you can see my screenshot, there is no metadata in payload?

**Comment by rikschennink** [comment]
afaik it doesn't show metadata there, it only appends metadata that is added to the file item, not the file information itself

**Comment by zshnb** [comment]
> afaik it doesn't show metadata there, it only appends metadata that is added to the file item, not the file information itself

is there anyway to add file information to file item when upload?

**Comment by rikschennink** [comment]
see docs

**Comment by zshnb** [comment]
> see docs

sorry I don't find it, could you please give me a link? I mean add automatically, not manually

**Comment by rikschennink** [comment]
https://pqina.nl/filepond/docs/api/plugins/file-metadata/

https://pqina.nl/filepond/docs/api/file-item/

https://pqina.nl/filepond/docs/api/instance/events/

Listen to "addfile" event then populate metadata with setMetadata
