### ISSUE TITLE
cant get base64 string Filepond Encode not working

### ISSUE THREAD

**Issue by laurenceschellevisch** [pqina/react-filepond#27]
#Summary:
I want to send a base64 string to an API.

##How to reproduce:
Filepond Code:
![image](https://user-images.githubusercontent.com/17025778/47366053-24e67680-d6dd-11e8-9b47-da4e79808cea.png)

result:
![image](https://user-images.githubusercontent.com/17025778/47365407-ca98e600-d6db-11e8-8b77-1d5ada4eee02.png)

in the result I use the function getFiles(); to get the object in the browser like that.
https://pqina.nl/filepond/docs/patterns/plugins/file-encode/

###Expected behaviour:
I thought I was supposed to get a base64 object like its saying in the filepond-encode link above.

####Additional information:

| Environment  | Version
|------------- | -----------
| OS           | Windows 10
| Browser      | Chrome  70.0.3538.67

**Comment by rikschennink** [comment]
Please don't post the same issue in multiple repositories.
https://github.com/pqina/filepond-plugin-file-encode/issues/3
