### ISSUE TITLE
Change labels through props

### ISSUE THREAD

**Issue by mastacheata** [pqina/react-filepond#31]
Hello,

I'd like to suggest exposing the labels for FilePond through the react component.
Currently FilePond is single language english and very generic. but at least you have the option to change the labels.
However in the React Component you need to change the labels AFTER rendering the component and then trigger a rerender.

If you'd expose the label properties of the filepond instance and set them accordingly in the React component, everyone could set their own labels and/or provide translated strings without having to trigger a surplus rerender.

**Comment by rikschennink** [comment]
Maybe I'm missing something but this works on my dev environment?

```jsx
<FilePond labelIdle="Hello World"></FilePond>
```

**Comment by mastacheata** [comment]
I didn't even try that to be honest.
So this is just a documentation omission.
I honestly thought you could only use those props that are documented. o.O

**Comment by mastacheata** [comment]
> I didn't even try that to be honest.
> So this is just a documentation omission.
> I honestly thought you could only use those props that are documented. o.O

Or maybe I misunderstood the docs, because with knowing this and rereading the docs, it's actually documented there and I just didn't interpret it like that.

**Comment by rikschennink** [comment]
The docs are open source so if you have any suggestions to make this more clear I’m all ears :)

**Comment by KEMAL-YILDIRIM** [comment]
Additional info about language support.
You can add language props in a seperate js file and change the whole language based explanation by that 
`import {FilePondLanguage} from './Language'`

Language.js -->
`export const FilePondLanguage = {`
`labelIdle:'You may choose your best explanation `
`<span class="filepond--label-action">Inspect</span>.',`
`}`

as a prop
`<FilePond {...FilePondLanguage}></FilePond>`

**Comment by ashoksudani** [comment]
@rikschennink : What can be a best way to add icon into drop area label?
e.g.I have a react component or image and I want to display it inside drop lable

- <img src="upload-icon /> Drag & Drop ..
- <ReactComponentSvgCloudUploadIcon /> Drag & Drop...

I tried to find options but I could not find a way for it. Please let me know if it is possible.

Thanks.

**Comment by rikschennink** [comment]
I think you can add it as plain HTML in the `labelIdle` string. Using a React component won't work unfortunately.

**Comment by ashoksudani** [comment]
Thanks Rik,

To achieve same what I did was:

-create component called UloadLabel and rendered it after component is mounted:

`  componentDidMount() {
    ReactDOM.render(
      <UploadLabel />,
      this.pondContainerRef.current.querySelector('.filepond--drop-label')
    );
  }`

- "pondContainerRef" is the ref I applied to parent element which is rendering FilePond component.

**Comment by sela** [comment]
> I think you can add it as plain HTML in the `labelIdle` string. Using a React component won't work unfortunately.

is it still the case you can't add a React Component?
