### ISSUE TITLE
File upload configuration

### ISSUE THREAD

**Issue by rowrowrowrow** [pqina/react-filepond#32]
Hello,

Thanks for the very cool uploading tool! Can you please explain the best way (if possible) to upload only a file without using a unique Id and temporary folder. (Can I simply overwrite the headers?)

Thanks!!!

To add further detail, I will be using custom Content-Type (Content-Type: application/octet-stream) and Content-Disposition headers in the upload request that differ from what I find in the documentation.

**Comment by rowrowrowrow** [comment]
Thanks for the response! The other request methods seems to rely on the uniqueFileId field. Should/can I tell filepond to use another value/field to use as the primary key for the file(s)?

**Comment by rikschennink** [comment]
You can return any value you like, FilePond doesn't use it, it's only there for you to identify the file on the client and the server.

**Comment by rowrowrowrow** [comment]
Thanks for your help and the great library!!!
