### ISSUE TITLE
Help With Z-Index

### ISSUE THREAD

**Issue by LiamSolDev** [pqina/react-filepond#34]
Hello,

I cannot find any functionality to edit or change the styling of the filepond. Has anyone attempted this before?
I just need to lower the z-index of both .filepond--drop-label to 0 and .filepond--root>.filepond--panel to -1, as the current z-index are causing conflicts with multiple components in my app.

Kind Regards,
Liam

**Comment by rikschennink** [comment]
All elements are positioned relative to the root FilePond element (which has `position:relative`) so changing the z-index of the root element should resolve any issues you have.

Can you make a screenshot of the problem?

**Comment by LiamSolDev** [comment]
Hi,

Thank you for your advice, it was enough to put me on the right train of thought to solve it.

Kind Regards,
Liam
