### ISSUE TITLE
No changelog or release notes

### ISSUE THREAD

**Issue by DominicTobias** [pqina/react-filepond#37]
Hi, I noticed this package went up 2 major versions last month, but there is no CHANGELOG.md or release notes under Releases. How are we supposed to know about what changed/breaking changes/fixes? Thanks

**Comment by rikschennink** [comment]
You're absolutely right, there should be a changelog. Will see if I can add one in the coming weeks.

**Comment by rikschennink** [comment]
I've added a changelog
