### ISSUE TITLE
filepond.min.css file NOT being applied

### ISSUE THREAD

**Issue by brave-merida** [pqina/react-filepond#39]
### Summary
Hi there,

```
import { FilePond } from 'react-filepond';
import 'filepond/dist/filepond.css';
...
<FilePond/>
```
I used above code, but got this ugly style.
![image](https://user-images.githubusercontent.com/30062357/49332200-94f0f200-f5e3-11e8-904a-31cec42bb23e.png)

Any suggestion?

### Additional information

| Environment  | Version
|------------- | -----------
| OS           | MacOS / Windows
| Browser      | Chrome latest

**Comment by rikschennink** [comment]
I don't know. This does not happen in my create-react-app test project (last time I checked).

Maybe the build script doesn't pick up files from node_modules?

You can try adding the files to the HTML template.

**Comment by brave-merida** [comment]
I added the css file link into HTML,
It works good.
Thanks.
