### ISSUE TITLE
FilePond.SetOptions not worked

### ISSUE THREAD

**Issue by seraj** [pqina/react-filepond#40]
i just use this code in my component to set custom server request with headers
```js
FilePond.setOptions({
    server: {
        url: '/uploader',
        process: {
            url: './process',
            method: 'POST',
            withCredentials: false,
            headers: {},
            timeout: 7000,
            onload: null,
            onerror: null
        }
    }
});
```

but it's  not worked for me.

this is the error 

Uncaught TypeError: react_filepond__WEBPACK_IMPORTED_MODULE_10__.FilePond.setOptions is not a function

**Comment by rikschennink** [comment]
With React the FilePond object is a component there is no global FilePond object available at the moment. You can pass the server properties to the component as a prop.

**Comment by rikschennink** [comment]
I’m on my mobile phone but I think this should do it:

```jsx 
<FilePond server={
{
        url: '/uploader',
        process: {
            url: './process',
            method: 'POST',
            withCredentials: false,
            headers: {},
            timeout: 7000,
            onload: null,
            onerror: null
        }
    }
}></FilePond>
```

**Comment by svahdati** [comment]
ops! is there any way to call Upload Request out of component props?
i need to handle 401 Error with axios.

**Comment by svahdati** [comment]
@rikschennink

**Comment by rikschennink** [comment]
You can set a custom processing method and handle the upload yourself.
https://pqina.nl/filepond/docs/patterns/api/server/#advanced

**Comment by spfx-dev-ang** [comment]
Hi,

I am using react filepond control in spfx webpart. 

I need to rename file after file upload before form data submit to the doc library. I tried below code, but it is not working.

any thoughts?

`// Import FilePond
import * as FilePond from 'filepond';

// Import the plugin code
import FilePondPluginFileRename from 'filepond-plugin-file-rename';

// Register the plugin
FilePond.registerPlugin(FilePondPluginFileRename);

FilePond.setOptions({
    fileRenameFunction: (file) => {
        return `my_new_name${file.extension}`;
    }
})`

**Comment by rikschennink** [comment]
@spfx-dev-ang Can you confirm the function actually runs by setting a breakpoint or console log statement?

**Comment by spfx-dev-ang** [comment]
Yes, it works only in the constructor. I have kept console statements inside the fileRenameFunction, it executed.

I moved the above piece of code inside constructor, and it worked. But I want this to be worked in button submit event.

Am I missing anything here?

**Comment by rikschennink** [comment]
If you're using React you can get a `ref` to the component and use that to update the options, no need to use `setOptions`.

**Comment by afilp** [comment]
How can we set the locale?

Example in non-react code:
```
import el_EL from 'filepond/locale/el-el.js';
FilePond.setOptions(el_EL);
```

How can we do this here?

Thanks!
