### ISSUE TITLE
allowRevert not working

### ISSUE THREAD

**Issue by brampurnot** [pqina/react-filepond#47]
Hello,

I want to disable the revert function. Therefore I have passed allowRevert={false}. However, this is not working and the 'X' icon is still there. Also when I click on it, Filepond is trying to call the DELETE method. 

Example code:
<img width="465" alt="screenshot 2018-12-29 at 13 24 30" src="https://user-images.githubusercontent.com/17197669/50538275-1731ef00-0b6d-11e9-8a92-dbf8ad476895.png">

And the result: 
<img width="613" alt="screenshot 2018-12-29 at 13 23 09" src="https://user-images.githubusercontent.com/17197669/50538267-f8335d00-0b6c-11e9-8bf6-0a7eae2b812d.png">

Any help is appreciated!
Bram

**Comment by rikschennink** [comment]
Judging from the code snippet you show it should work.

I tested it on my dev env and it works correctly there.

![screenshot 2019-01-02 at 10 21 28](https://user-images.githubusercontent.com/1132575/50586085-4b145980-0e78-11e9-8d71-77f9896373bd.png)

I'd need to see a minimal test case to determine the problem.

**Comment by brampurnot** [comment]
Issue can be closed. It was caused by a custom CSS file.
