### ISSUE TITLE
Click to view uploaded item ?

### ISSUE THREAD

**Issue by Taerarenai** [pqina/react-filepond#49]
### Summary
I'm using react-filepond on an Edit form which takes information from a secured rest api (with `Bearer accesstoken`)
Due to the nature of the call i am actually just mocking the files in `<File>` with name from the rest-api.

What i'd like is for a way to click the file name and have it open the url on which it resides (since its on a different site and users need to be logged in there). Is there any way to do that? Is there any event for on-click ? 

Adding anything around `<File>` or even `onClick` does nothing (`<a>` around `<File>` actually changes the src of `<File>`).

### How to reproduce
Create FilePond file with mock data.

```
{this.state.selectedFiles.map(file => (
<File key={file} src={file} name={file.FileName} size={700100} type="AttachedFile" origin="local" />
))}
```
### Expected behaviour

A handler so the user can be redirected to the files in the list by clicking on file name or on a `View` button.

### Additional information

| Environment  | Version
|------------- | -----------
| OS           | Windows
| Device       | Desktop
| Browser      | Chrome

**Comment by rikschennink** [comment]
The `<File>` object is a mapping to the internal files array, it's not really used for markup, there is currently no way to alter the HTML without writing a custom FilePond plugin. Another user has managed to pull it off without docs: https://github.com/pqina/filepond/issues/52

You could try to listen for click events on the editor and figure out where the user clicked but that might be tricky.
