### ISSUE TITLE
Docs: https://pqina.nl/filepond/docs/patterns/frameworks/react/ - Broken Link

### ISSUE THREAD

**Issue by drazisil** [pqina/react-filepond#5]
Hi!

I couldn't find your docs site for a PR, but on https://pqina.nl/filepond/docs/patterns/frameworks/react/ the link `FilePond instance methods` points to `http://localhost:1313/patterns/api/filepond-instance/#methods`

That's um, kinda not reachable online. ;)

Perhaps you meant to link to `https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#methods` ?

**Comment by rikschennink** [comment]
Haha, you're right, accidental link to the internal dev version. I've fixed the mistake and pushed the new docs.

Good idea to make a repository for the docs will do so in the near future.
