### ISSUE TITLE
Use processFile with a function that handles the upload rather than a direct Post?

### ISSUE THREAD

**Issue by phil-repo** [pqina/react-filepond#50]
Hey there,

I'm currently using filepond on a react page and it's awesome! I've run into a bit of difficulty recently however.

The current process I'm trying to achieve is:

User drops file onto filepond => file contents are converted to a json string => a function takes this json string and posts it to a remote server (this function handles the authentication as well).

Currently I've got something that works by doing the following:

```js
onaddfilestart={(file) => {          
   if (file.status === 2) {
   //my custom upload method takes the file and processes it;
}
```                     

This isn't very good however as the filepond UI doesn't update at all (I'm currently just showing a success message div if my upload method completes). 

I've looked at the docs around using `server` and custom processing, but this all seems to only be useable if you want to **directly upload the file itself** to a remote location using `XMLHttpRequest`.

I'd like to be able to do the process I described above and still have the same UI effect that `processFile` triggers (turns green shows the uploading wheel and updates to complete when the process has finished).

Is there any mechanism in FilePond for me to be able to do this easily? Apologies if I seem to have misunderstood anything here or I'm not being clear. I come from a dev background but I'm extremely new to javascript (only a few days so far).

**Comment by rikschennink** [comment]
You can do anything you want in the `server.process` method. As long as you call `load` at the end it's fine for FilePond. You can still upload the files in a later step if you wish.

**Comment by phil-repo** [comment]
Ah, I missed this. I just gave it a try and it worked perfectly, thanks!

I had one last question, I've resized the FilePond component a bit but it now looks like:

![filepondscroller](https://user-images.githubusercontent.com/40392885/51130464-f46a3080-1824-11e9-9c87-65b87324c045.PNG)

Do you know how I can get rid of the scroller and make it so that the whole file can be seen in the box? I've tried for a good hour or so changing different heights etc on different css classes but no luck. I've seen some lovely examples of FilePond in use online so I know it's possible.

**Comment by rikschennink** [comment]
It seems like it either has a `height` or a `max-height` style which will cause it to render a scrollbar if the height is exceeded.
