### ISSUE TITLE
FilePondPluginImageTransform using transform variants problem

### ISSUE THREAD

**Issue by lwxtd** [pqina/react-filepond#51]
i dont know how to implement variants for plugin

i am useing this code :

import { FilePond, File, registerPlugin } from 'react-filepond';
import FilePondPluginImageResize from 'filepond-plugin-image-resize';
import FilePondPluginImageValidateSize from 'filepond-plugin-image-validate-size';
import FilePondPluginFileValidateSize from 'filepond-plugin-file-validate-size';
import 'filepond/dist/filepond.min.css';
import FilePondPluginImagePreview from 'filepond-plugin-image-preview';
import 'filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css';
import FilePondPluginImageTransform from 'filepond-plugin-image-transform';
registerPlugin(FilePondPluginImageResize,
    FilePondPluginImagePreview,
    FilePondPluginImageValidateSize,
    FilePondPluginFileValidateSize,
    FilePondPluginImageTransform
    );

const variants=({
    'thumb_smddall_': transforms => {
        transforms.resize.size.width = 200;
        return transforms;
    }
});

    <FilePond
                        allowMultiple={true}
                        maxFiles={10}
                        server={Server}
                        maxParallelUploads={1}
                        allowImagePreview={true}
                        imageValidateSizeMinWidth={200}
                        imageValidateSizeMinHeight={200}
                        imageValidateSizeMaxWidth={8000}
                        imageValidateSizeMaxHeight={8000}
                        imageResizeTargetWidth={1800}
                        imageResizeTargetHeight={1200}
                        imageResizeUpscale={false}
                        maxFileSize={'8MB'}
                        maxTotalFileSize={'30MB'}
                        allowImageTransform={true}
                        imageTransformOutputQuality={65}
                        imageTransformVariants= {variants}

                    />

every plugin just works fine but when i add variant it stop working and show just loading on image upload

**Comment by lwxtd** [comment]
after removing space still nothing change :(

**Comment by lwxtd** [comment]
> 
> 
> i dont know how to implement variants for plugin
> 
> i am useing this code :
> 
> import { FilePond, File, registerPlugin } from 'react-filepond';
> import FilePondPluginImageResize from 'filepond-plugin-image-resize';
> import FilePondPluginImageValidateSize from 'filepond-plugin-image-validate-size';
> import FilePondPluginFileValidateSize from 'filepond-plugin-file-validate-size';
> import 'filepond/dist/filepond.min.css';
> import FilePondPluginImagePreview from 'filepond-plugin-image-preview';
> import 'filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css';
> import FilePondPluginImageTransform from 'filepond-plugin-image-transform';
> registerPlugin(FilePondPluginImageResize,
> FilePondPluginImagePreview,
> FilePondPluginImageValidateSize,
> FilePondPluginFileValidateSize,
> FilePondPluginImageTransform
> );
> 
> const variants=({
> 'thumb_smddall_': transforms => {
> transforms.resize.size.width = 200;
> return transforms;
> }
> });
> 
> ```
> <FilePond
>                     allowMultiple={true}
>                     maxFiles={10}
>                     server={Server}
>                     maxParallelUploads={1}
>                     allowImagePreview={true}
>                     imageValidateSizeMinWidth={200}
>                     imageValidateSizeMinHeight={200}
>                     imageValidateSizeMaxWidth={8000}
>                     imageValidateSizeMaxHeight={8000}
>                     imageResizeTargetWidth={1800}
>                     imageResizeTargetHeight={1200}
>                     imageResizeUpscale={false}
>                     maxFileSize={'8MB'}
>                     maxTotalFileSize={'30MB'}
>                     allowImageTransform={true}
>                     imageTransformOutputQuality={65}
>                     imageTransformVariants= {variants}
> 
>                 />
> ```
> 
> every plugin just works fine but when i add variant it stop working and show just loading on image upload

**Comment by rikschennink** [comment]
> every plugin just works fine but when i add variant it stop working and show just loading on image upload

To be able to help out I need more information, like errors in your developer console, a public test case (preferably not react as it’s related to the plugin), info on browsers used to test.

**Comment by dinorhythms** [comment]
How do i implement the transform plugin in react please?
