### ISSUE TITLE
Expandable gray background not showing and not responding to new files being added

### ISSUE THREAD

**Issue by rockyhuber** [pqina/react-filepond#52]
### Summary
Expandable gray background not showing and not responding to new files being added

### How to reproduce
Just install filepond without any plugins, replicate code provided on main React FilePond page.

### Expected behaviour
Background box will expand to fit newly added files

### Additional information

| Environment  | Version
|------------- | -----------
| OS           | MacOS / Windows / iOS / Linux / ...
| Device       | iPhone SE / Galaxy Note 9 / ...
| Browser      | Safari 11.1.1 / Edge 15 / ...

**Comment by rikschennink** [comment]
Just to be sure, I've just created a new React app.

```
create-react-app foo

cd foo

npm install react-filepond filepond --save

npm start
```

Copy pasted in the code from the front page, replacing the original `App` component in `src/App.js` and imported the required styles and scripts.

Refreshed the page at `http://localhost:3000`, and it works as intended.

![screenshot 2019-01-17 at 08 02 46](https://user-images.githubusercontent.com/1132575/51301099-4c27b800-1a2e-11e9-900a-edece36fdacf.png)

I'll need more information before we can investigate further.

**Comment by rockyhuber** [comment]
This is my current code base for the component:

`import React, {Component, Fragment} from "react";
import {connect} from "react-redux";
// import { createAction } from "../actions";
import { FilePond, File, registerPlugin } from 'react-filepond';
import 'filepond/dist/filepond.min.css';
import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type';
import FilePondPluginFileValidateSize from 'filepond-plugin-file-validate-size';

registerPlugin(FilePondPluginFileValidateType, FilePondPluginFileValidateSize);

const mapStateToProps = state => {
 return {
   // some props
 };
};

const mapDispatchToProps = dispatch => {
 return {
 // some redux actions
 };
}

class compTemp extends Component {
  constructor(props) {
    super(props);
    this.state = {
      files: ['index.html']
    };
  }

  handleInit = () => {
  }

  render() {
    return (
      <Fragment>
        <div>File uploader</div>
          <FilePond
            ref={ref => this.pond = ref}
            allowMultiple={true}
            maxFiles={3}
            server="http://localhost:9000/audio/uploads"
            oninit={() => this.handleInit()}
            acceptedFileTypes={['audio/mpeg3', 'audio/x-mpeg-3', 'video/mpeg', 'video/x-mpeg', 'audio/aac', 'audio/wav', 'audio/mp4', 'video/mp4']}
            fileValidateTypeDetectType={(source, type) => new Promise((resolve, reject) => {
              console.log(source);
              console.log(type);
                // Do custom type detection here and return with promise
                resolve(type);
            })}
            allowFileSizeValidation={true}
            maxTotalFileSize={'1000MB'}
            onupdatefiles={(fileItems) => {
              // Set current file objects to this.state
              this.setState({
                  files: fileItems.map(fileItem => fileItem.file)
              });
            }}>
          {/* Update current files  */}
          {this.state.files.length > 0 && this.state.files.map(file => (
            <File key={file} src={file} origin="local" />
          ))}
        </FilePond>
      </Fragment>
    );
  }
}

export default connect(
    mapStateToProps,
    mapDispatchToProps
)(compTemp);
`
I ejected the application to have greater control and to activate a number of modules that required an ejected app.

This is what I see:
![alt text](https://cl.ly/5df11c2af3a0)

**Comment by rikschennink** [comment]
I don't know, maybe the height is affected by a parent control.

I advise to make a fresh install with create-react-app and compare side by side. 

Or, create a public test case.
