### ISSUE TITLE
How to display the fileName instead of serverId 

### ISSUE THREAD

**Issue by SpawnAtis** [pqina/react-filepond#53]
Hi

How can I restore the filename ? 

```
<FilePond
    server={{
       url: 'https://localhost:8443/api',
       load: {
          url: '/fileLoad/',
	  method: 'GET',
	  withCredentials: true,
      }
     }}
 >
    <File source="724" type="local" />
</FilePond>
```

![image](https://user-images.githubusercontent.com/23311140/51479143-81216b00-1d9e-11e9-9c16-881ced658fc4.png)

![image](https://user-images.githubusercontent.com/23311140/51479178-94ccd180-1d9e-11e9-8d42-edb01eb07bed.png)

Thx

**Comment by rikschennink** [comment]
The code looks okay, as does the `Content-Disposition` header. No errors in your developer console?

**Comment by rikschennink** [comment]
Yes, with CORS custom headers are stripped, annoying but more secure. If the issue has been fixed you may close it.
