### ISSUE TITLE
FilePond.setOptions() method not working 

### ISSUE THREAD

**Issue by sabbin** [pqina/react-filepond#54]
Hello,

### Summary
I am trying to use the `setOptions` method in order to set the `captureMethod` after the FilePond instance was initialised. Following the documentation on the [website](https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#setting-options), after I call the `setOptions` method I get  `TypeError: _this.fileUpload.current.setOptions is not a function`. 

![screenshot_2019-01-30 react app](https://user-images.githubusercontent.com/12841157/51984743-ba479280-24a4-11e9-8c7e-5492d0016b6f.png)

If I open the FilePond instance in the console, I also cannot see the `setOptions` as a function of the instace

![obj](https://user-images.githubusercontent.com/12841157/51984718-a9971c80-24a4-11e9-9c26-6a2708ec90bf.png)

The `browse` method which is used in the next line works(there is also the browse function in the FilePond instance obj in the screenshot)

### Expected behaviour

I would like to set the `captureMethod` after the FilePond instance has been created through the `setOptions` method

### Additional information

Is there another way of doing this after he Filepond instance was created? I tried to set the `captureMethod` through a state object but I does not overwrite the initial setting.

| Environment  | Version
|------------- | -----------
| OS           | MacOS / Windows / iOS / Linux / ...
| Device       | iPhone SE / Galaxy Note 9 / ...
| Browser      | Safari 11.1.1 / Edge 15 / ...

**Comment by rikschennink** [comment]
The `props` set to the FilePond component are automatically passed to the internal `setOptions` method so therefor the method is not available on React.

The fact that it’s not updating the attribute it probably a problem of FilePond itself. I’ll look into this ASAP.

**Comment by rikschennink** [comment]
@sabbin I just tested with core FilePond and it does update the attribute when it's updated. So updating a prop linked to a state should work.

```jsx
<FilePond captureMethod={this.state.captureMethod}></FilePond>
```

**Comment by sabbin** [comment]
@rikschennink

I will try to explain what I am trying to achieve, maybe I am applying a wrong logic, or something else is wrong. On my page I want to have 2 buttons, one to take a picture, and one to upload the picture. When you click on one, it should set the `captureMethod` to either `user` for camera or `filesystem` for upload and automatically 
open the browse.

The two buttons both `onClick` call a `setCaptureType` function 

    setCaptureType = (captureType) => {
        this.setState({
            showContainer: true,
            label: 'Click to ${captureType === 'user' ? 'take' : 'select'} photo <span class="filepond--label-action"> here </span>',
            captureType,
        }, this.fileUpload.current.browse);
    };

The `setCaptureType` sets the state and then call the `browse` method on the filePond instance via reference. When the `browse` method is called in the callback of the `setState` it takes the `captureMethod` that I have initially in the state... If it's _user_ or _fi it remains like that even if I change it in the `setCaptureType`... That is why I said that this is not working even through `state`, I tested this on iOS(safari) and android(chrome)

Is there a way to launch the browse automatically? Then I would not require to call it via reference on the callback

**Comment by rikschennink** [comment]
But is `this.state.captureType` set to `<FilePond captureMethod={this.state.captureType}>`?

**Comment by sabbin** [comment]
Yes, it is, `captureMethod={captureType}` where `const {captureType} = this.state`

**Comment by rikschennink** [comment]
I can see the `capture` attribute on the internal file input changing from `'user'` to `'environment'` in my test case.

![screenshot 2019-01-31 at 13 16 50](https://user-images.githubusercontent.com/1132575/52053782-95adf200-255a-11e9-8ba7-a4579c62aed0.png)

**Comment by sabbin** [comment]
Actually it does, this is strange.. Maybe the `browse` is called before the `state` is changed on the mobile versions. Is there a way to trigger the `browse` from `init` or some other way?

**Comment by rikschennink** [comment]
You could run `console.log(document.querySelector('.filepond--browser').getAttribute('capture'))` in your callback and see if it has been updated already. I expect it hasn't.

Please note that `browse` only works if the user has initiated the action, otherwise it's blocked by the browser for security reasons.

**Comment by sabbin** [comment]
I know... That's why I have the 2 buttons, in order to have a user action to trigger the browse... I'll look for other work arounds

**Comment by sabbin** [comment]
Thank you @rikschennink for all the help, I'll close the issue here, the problem is in my implementation

**Comment by rikschennink** [comment]
@sabbin Okay, I think you could create two file inputs and then listen for onchange on the inputs and feed file objects to FilePond.
