### ISSUE TITLE
Found an issue on IOS [react js]

### ISSUE THREAD

**Issue by srs3301** [pqina/react-filepond#55]
Hello, we just started working with filepond a few days back. It's just works very smoothly on different platforms, but we are facing an issue on IOS. While we try to upload a file from iphone 5s, it got stuck at uploading process and no further progress is made...

Hope you will figure it out soon..
Anyway, it's an amazing tool..

(screenshot given)
![img_0107](https://user-images.githubusercontent.com/47245277/52122429-f9164d80-2648-11e9-9628-d2a3ea70b431.PNG)

| Environment  | Version
|------------- | -----------
| Device       | iPhone 5s /

**Comment by rikschennink** [comment]
Can you supply remote debug information, any messages that show up in safari dev tools?

**Comment by srs3301** [comment]
Ok....
i'm leaving two screenshots here, one with the successful case and other with iphone's case.
![new3](https://user-images.githubusercontent.com/47245277/52126029-36cca380-2654-11e9-9c28-a5d6e75ee6c8.jpg)
![screen shot 2019-02-01 at 6 33 11 pm](https://user-images.githubusercontent.com/47245277/52126031-36cca380-2654-11e9-809b-b8c6b4bde85d.jpg)

**Comment by rikschennink** [comment]
I think one of the screenshots might be missing?

**Comment by srs3301** [comment]
Actually both the screenshot are given

**Comment by srs3301** [comment]
Actually no errors occurred while uploading....

**Comment by rikschennink** [comment]
If there are no errors in the developer console, then it's difficult to tell what might be wrong.

**Comment by srs3301** [comment]
<FilePond name='profile_pic'  
        allowFileTypeValidation={true} acceptedFileTypes={['image/jpg','image/jpeg']}
        allowMultiple={false} maxFiles={1} 
        server={{
          url:'ajax/update_profile_picture_byadmin',
          process:{ 
            url:'',
            ondata:(formData)=>{
              //formData.append('profile_pic',formData,formData.name)
              formData.append('id', this.props.admin.edituserid);
              return formData
            },
            onload:(response)=>{
              let res=JSON.parse(response); 
              this.props.dispatch(setAdminData('edituserpic', res.file_name))
            }
          }
        }}
        onprocessfile={()=>this.handleAdded()}
        />

**Comment by srs3301** [comment]
<FilePond name='profile_pic'  
        allowFileTypeValidation={true} acceptedFileTypes={['image/jpg','image/jpeg']}
        allowMultiple={false} maxFiles={1} 
        server={{
          url:'ajax/update_profile_picture_byadmin',
          process:{ 
            url:'',
            ondata:(formData)=>{
              //formData.append('profile_pic',formData,formData.name)
              formData.append('id', this.props.admin.edituserid);
              return formData
            },
            onload:(response)=>{
              let res=JSON.parse(response); 
              this.props.dispatch(setAdminData('edituserpic', res.file_name))
            }
          }
        }}
        onprocessfile={()=>this.handleAdded()}
        />

**Comment by srs3301** [comment]
`<FilePond name='field_name'`
`allowFileTypeValidation={true} acceptedFileTypes={['image/jpg','image/jpeg']}`
``

**Comment by srs3301** [comment]
I think I figured it out. 

`        <FilePond name='field_name' `
`        allowFileTypeValidation={true} acceptedFileTypes={['image/jpg','image/jpeg']}`
`        allowMultiple={false}  `
`        server={{`
`         url:'/api',`
`          process:{`
`            url:'',`
`            ondata:(formData)=>{`
`              //formData.append('field_name)',formData,formData.name)`
`              return formData     `        
`            }        `    
`          }`
`        }}`
`        onprocessfile={()=>{this.handleAdded()}}`
`        /> `

I think a conflict by occurred by field name provided in prop section and formdata section. After removing the formdata section for field name, it started working in iphone.

But the problem is, without removing formdata section it was working for other platforms, only this case was occurred in iphone... 

Anyway thanks for your quick response and it is an amazing tool....

**Comment by srs3301** [comment]
I think I figured it out. 

`        <FilePond name='field_name' `
`        allowFileTypeValidation={true} acceptedFileTypes={['image/jpg','image/jpeg']}`
`        allowMultiple={false}  `
`        server={{`
`         url:'/api',`
`          process:{`
`            url:'',`
`            ondata:(formData)=>{`
`              //formData.append('field_name)',formData,formData.name)`
`              return formData     `        
`            }        `    
`          }`
`        }}`
`        onprocessfile={()=>{this.handleAdded()}}`
`        /> `

I think a conflict is occurred by field name provided in prop section and formdata section. After removing the formdata section for field name, it started working in iphone.

But the problem is, without removing formdata section it was working for other platforms, only this case was occurred in iphone... 

Anyway thanks for your quick response and it is an amazing tool....

**Comment by softwaregoat** [comment]
I cant run this on IOS browser. Please show me if you have any solution.
