### ISSUE TITLE
Video Upload

### ISSUE THREAD

**Issue by cngeru** [pqina/react-filepond#56]
Is there a video upload plugin to check video file size and the video's length ??

**Comment by rikschennink** [comment]
Hi, there currently is not, file size could be checked with the validate-file-size plugin. Would be an interesting addition to have video length validation as well.

**Comment by Brian611** [comment]
I think this is a crucial feature to have.

**Comment by JoeyEamigh** [comment]
Hey! I know this is old but I needed video length validation, so I wrote a quick plugin to handle it.

<https://www.npmjs.com/package/filepond-plugin-validate-video-length>
<https://github.com/JoeyEamigh/filepond-plugin-validate-video-length>

Just in case anyone happens across this issue and also needs it.

**Comment by rikschennink** [comment]
@JoeyEamigh Thanks for building this Joey!
