### ISSUE TITLE
this.pond.getFiles is not a function?

### ISSUE THREAD

**Issue by michaelcuneo** [pqina/react-filepond#61]
### Summary

I have two file ponds in my project... this.featurePond, and this.galleryPond
```js
this.featurePond = React.createRef();
this.galleryPond = React.createRef();
```

Before saving, I'm trying to get a normal file blob from the FilePond, ... it appears as though the state object isn't similar to a file blob at all, but I need it to be a file blob to upload to S3, but getFiles() doesn't work no matter how I instantiate the object at all... 

### How to reproduce

Cannot access getFiles from any method of instantiated this.pond.

### Expected behaviour

Expect to be able to get a file back from this.featurePond.getFiles();

### Additional information

| Environment  | Version
|------------- | -----------
| OS           | MacOS / Windows / iOS / Linux / ...
| Device       | iPhone SE / Galaxy Note 9 / ...
| Browser      | Safari 11.1.1 / Edge 15 / ...

**Comment by rikschennink** [comment]
It's not clear to me if you've also added the `ref={this.myRef}` to the `<FilePond>` component.

**Comment by michaelcuneo** [comment]
I have, it has been made in the React 16 manner, where references need to be created in this manner... 

I left the other part out though by mistake in this post.

### Constructor 
```
this.featurePond = React.createRef();
```

### FilePond Component
```
                <FilePond
                  ref={this.featurePond}
                  allowMultiple={false}
                  files={this.state.featureFile}
                  maxFiles={10}
                  onupdatefiles={fileItems => {
                    this.setState({
                      featureFile: fileItems.map(fileItem => fileItem.file),
                    });
                  }}
                />
```

**Comment by rikschennink** [comment]
Okay, and `this.featurePond.getFiles()` is not returning any files (but the files are visible)?

**Comment by michaelcuneo** [comment]
It's stating that this.featurePond.getFiles() is not a function.

But if I look at this.state.featureFile... it has data, and files. 

I was trying to form or receive a File, like I'd receive from <input type="file" ... to use in an S3 Upload.

**Comment by rikschennink** [comment]
Use `this.featurePond.current.getFiles()`

I don't know why React adds the current property but it does when using `createRef`.

Tip: use `console.log(this.featurePond)` to view the object itself, this way you can easier determine what's going on and how you could fix it.
