### ISSUE TITLE
Manually upload file, convert to blob instead of base64

### ISSUE THREAD

**Issue by rockyhuber** [pqina/react-filepond#62]
Hi, I am trying to upload large files manually on submission of a formik form. I have got it to work by converting the filepond file to a base64, and then uploading that. However having an issue with large base64 files being too long to upload and process on the server. I would like to convert the filepond file to a blob instead, and then send that directly to the server. Any suggestions greatly appreciated?

**Comment by rikschennink** [comment]
It's impossible to create a file object in the browser and then send it along with a classic form post.

You either have to encode it, or you have to send it asynchronously.

**Comment by rockyhuber** [comment]
Thank you for quick reply. 

Are you referring to the https://pqina.nl/filepond/docs/patterns/api/server/#advanced - setOptions code?

Or.

the configuration code above? https://pqina.nl/filepond/docs/patterns/api/server/#configuration

I want to post it using a formik submit button.

**Comment by rikschennink** [comment]
If you want to post along with the form then you'll have to use the file encode plugin.
https://pqina.nl/filepond/docs/patterns/plugins/file-encode/

> When we want to submit files along with the classic form post we run into a serious browser limitation. The file input field is the only field available to submit files to a server but its value cannot be set. The file input field value can only be modified by the user by manually adding files (in one action).

**Comment by rockyhuber** [comment]
Oh ok, though you wouldn't recommend using this method to upload larger files, say 100mb +?

**Comment by rikschennink** [comment]
No, I think you're already going to run into trouble with files size around 500KB

**Comment by rockyhuber** [comment]
Oh. In that case I may have to use another library. Thank you so much for the awesome library anyway and for quick response times. This library will go far. Will definitely use elsewhere were appropriate.

**Comment by rikschennink** [comment]
Thanks! And, no problem, always happy to help :-) Please note that other libraries will have the same problem as this is a browser limitation.

For future devs stumbling upon this thread. You can certainly upload big files with FilePond but you'll have to do it asynchronously using the `server` property OR by asynchronously submitting the parent form.

As long as browser vendors don't allow writing File objects to the file input we can't do classic form submits.

**Comment by shierro** [comment]
Hi @rockyhuber can you help provide an example usage, to manually trigger upload, and use filepond's progress UI?

**Comment by MoshinaT** [comment]
> Hi, I am trying to upload large files manually on submission of a formik form. I have got it to work by converting the filepond file to a base64, and then uploading that. However having an issue with large base64 files being too long to upload and process on the server. I would like to convert the filepond file to a blob instead, and then send that directly to the server. Any suggestions greatly appreciated?



hi, i am trying the same. did you pass just the base64 to backend along with data type and retrieve else sent the full filepond instance?
