### ISSUE TITLE
serverId is undefined

### ISSUE THREAD

**Issue by violabg** [pqina/react-filepond#68]
### Summary
I'm trying to use the server revert method. From what I understand i need to be call with the serverId.
the problem is that serverId is undefined

### How to reproduce
this is my config
```jsx
const onLoaded = response => {
    console.log("onLoaded", response); // it print the id returned by the server
  };

const onProcessFile = (error, file) => {
    console.log("onProcessFile", file); // prints file ok
    console.log("onProcessFile id", file.id); // prints file.id ok
    console.log("onProcessFile serverId", file.serverId); // it prints undefined
  };

<FilePond 
   server={{
              url: `${domain}/api/insert_img`,
              process: {
                onload: onLoaded
              }
    }} 
    onprocessfile={onProcessFile}
/>
```

### Expected behaviour

```jsx
const onProcessFile = (error, file) => {    
    console.log("onProcessFile", file);
    console.log("onProcessFile id", file.id);
    console.log("onProcessFile serverId", file.serverId); // should print the serverId
  };
```

### Additional information

is there some step that I'm missing?

| Environment  | Version
|------------- | -----------
| OS           | MacOS / Windows / Linux / ...
| Browser      | All / ...

**Comment by rikschennink** [comment]
`onload` should return the server id. It's only there to filter the server response.

```js
const onLoaded = response => {
  console.log("onLoaded", response); // it print the id returned by the server
  return response;    
};
```

**Comment by violabg** [comment]
in my case onload does return the server id.
the problem I'm having is that the revert method does not pass any argument to the server. I'm assuming it's because the serverId of the file is undefined  

`console.log("onProcessFile serverId", file.serverId); // it prints undefined`

**Comment by violabg** [comment]
who is responsible to set serverId?

**Comment by rikschennink** [comment]
Your server should return a server file id in the response to this request `${domain}/api/insert_img`, that id is then assigned by FilePond to `file.serverId`

**Comment by violabg** [comment]
thanks, but that is my problem, it does not.

`
const onLoaded = response => {
  console.log("onLoaded", response); // it print the id returned by the server
  return response;    
};
`

I'm getting back the server id in text/plain, and I'm able to console log it to verify it exist:

`onLoaded 102025`

**Comment by violabg** [comment]
I have created codesandbox.io to reproduce the issue

has you can see from the console log file.serverId is undefined

https://codesandbox.io/s/zqvj2xwv84

**Comment by rikschennink** [comment]
As stated earlier, if you use the `onload` callback on the `response` property you have to return the response to FilePond. Logging the server id but not returning it is causing this problem.

Change this
```js
const onLoaded = response => {
  console.log("onLoaded", response); // it print the id returned by the server
};
```

To this

```js
const onLoaded = response => {
  console.log("onLoaded", response); // it print the id returned by the server
  return response;    
};
```

**Comment by violabg** [comment]
thank you so much, that what I was missing
