### ISSUE TITLE
Conflict of label variables and js-lingui

### ISSUE THREAD

**Issue by SilentImp** [pqina/react-filepond#69]
### Summary

Both react FilePond and [lingui.js](https://lingui.js.org/) use `{}` chars to mark variables.
When you try to add FilePonf label for translations you get an error because lingui expect you will pass a value of the variable, but it actually FilePond variable.

### How to reproduce

```javascript
<FilePond
…
labelMaxFileSize={i18n._(t`Maximum file size is {filesize}`)} />

```

### Expected behaviour

It would be nice to set chars that mark variables in FilePond label explicitly.
For example:
```javascript
<FilePond
…
variableOpenMark="["
variableCloseMark="]"
labelMaxFileSize={i18n._(t`Maximum file size is [filesize]`)} />

```

**Comment by rikschennink** [comment]
I would advise to open an issue at lingui and ask if they have a way to escape special characters.

**Comment by SilentImp** [comment]
Done.
https://github.com/lingui/js-lingui/issues/457

Am I right and there is no hope to solve problem from FilePond side?

**Comment by rikschennink** [comment]
@SilentImp Thanks!

I think it would be weird to have to adjust FilePond's language parsing. What if another library does this as well, do they need to change their logic also, or if your translating mustache template docs (where you're bound to run into trouble as well). Chances are you're going to run into other situations where lingui needs to ignore the `{` and `}` characters.
