### ISSUE TITLE
Question: How to Pre-load (fetch) Images

### ISSUE THREAD

**Issue by coommark** [pqina/react-filepond#71]
I must apologize that this is not a bug but a question. 

I am trying to pre-load a profile picture for a user. So my user object has an image url like this `http://localhost:8080/api/static/images/user-img.png`. So to show the image in Filepond, I am trying like this:

```jsx
<FilePond ref={ref => this.pond = ref}
      files={this.state.files}      
      allowMultiple={false}
      acceptedFileTypes="image/jpeg, image/png"                                                
      server={ serverConfig }
      onupdatefiles={(fileItems) => {
      this.setState({
            files: fileItems.map(fileItem => fileItem.file)
      	});
      console.log(this.state)
      }}>
</FilePond>
```
and my serverConfig is like this:

```js
const serverConfig = {
       url: "/api",
       load: (uniqueFileId, load, error, progress, abort, headers) => {
           fetch('http://localhost:8080/api/static/images/user-img.png').then(res => {
              console.log(res)
              res.blob()
           }).then(load)
       },
       process: {
           url: "/upload",
           onload: (response) => {
                console.log(response)
            }
       },
};
```
This is not working, as no image shows in the pond area. I also attempted this method: 

```js
files: [
        {
          source: "index.html",
          options: {
            type: "local"
          }
        }
]
```
But how do I pass the image url to this way of doing it? Making the URL as the source still fails. Thank you.

**Comment by rikschennink** [comment]
The value of `source` (`index.html`) will be passed to the `load` method.

Set `source` to `user-img.png` and `uniqueFileId` should now be `user-img.png`, then you can alter the url in `fetch` to `'http://localhost:8080/api/static/images/' + uniqueFileId`. That should work.

I think you also need to `return` the `res.blob()` promise in the `fetch` statement.

Please check if you're not getting any CORS errors in your developer console.

Btw, you also need to add a `return` statement to the `process.onload` callback.

```js
onload: (response) => {
    console.log(response)
    return response;
}
```

**Comment by sabbin** [comment]
@rikschennink 
Hi, I'm writing to you here even if it's closed, the question is related to this one.

I am trying to preload an image... Following the above code I've ended up with the following


    serverConfig = {
      process: this.handleProcess,
      revert: this.handleRevert,
      files: [
          {
            source: 'logo.png',
            options: {
              type: 'local',
            },
          },
        ],
        load: (uniqueFileId, load, error, progress, abort, headers) => {
          fetch(`${mediaUrl}\\${uniqueFileId}`).then((res) => {
            console.log(res);
            res.blob();
          }).then(load);
        },
        onload: (response) => {
          console.log(response);
          return response;
        },
    };

This is returned on the `this.generateServerConfig()` and it's used in the `FilePond` instance below

     <FilePond
          allowMultiple
          maxFiles={maxFiles}
          acceptedFileTypes={['image/*']}
          imageTransformOutputMimeType="image/png"
          imageTransformOutputQuality={100}
          server={this.generateServerConfig()}
          onupdatefiles={(fileItems) => {
            this.setState({
              files: fileItems.map(fileItem => fileItem.file),
            });
          }}
        >
          {files.map(file => (
            <File key={file} src={file} origin="local" />
          ))}

      </FilePond>

The issue is that neither the `fetch` is called nor any `console.log` are triggered.

Can you please tell me what is wrong here or if there is another way of doing this.

**Comment by rikschennink** [comment]
You need to return the `res.blob()` in your `fetch`.

Your server config shouldn't have a `files` property, files is a prop of the `<FilePond/>` component.

**Comment by sabbin** [comment]
Thanks for the reply!

I've updated my `serverConfig` as you said

```js
serverConfig = {
    process: this.handleProcess,
    revert: this.handleRevert,
    load: (uniqueFileId, load, error, progress, abort, headers) => {
        fetch(`${mediaUrl}\\${uniqueFileId}`).then((res) => {
            console.log(res);
            return res.blob();
         }).then(load);
    },
    onload: (response) => {
        console.log(response);
        return response;
    },
};
```

The problem is that `fetch` method is not triggered at all. The `console.log(res)` in the `callback` is not reached at any point. I don't get anything in the `console` and in the `network` tab I don't see any `call` for the media image.

**Comment by rikschennink** [comment]
what happens if you move the `console.log` to before the `fetch`

**Comment by sabbin** [comment]
Nothing, the `load` method is not triggered at all

**Comment by rikschennink** [comment]
@sabbin Please supply an public test case on codesandbox.

**Comment by michaelcuneo** [comment]
I'm having the exact same issue. Works 100% fine locally, but not online.

**Comment by michaelcuneo** [comment]
load does not trigger at all... locally it does, but once I build the app and upload to Amazon S3... it fails.
