### ISSUE TITLE
Fetch is not called

### ISSUE THREAD

**Issue by nbvora** [pqina/react-filepond#72]
Filepond fetch method is not getting called.

Configure filepond component. In server I have provided process and fetch custom implementation. While selecting file process is getting called. But after that fetch is not executing

`
uploadImage = (fieldName, file, metadata, load, error, progress, abort) => {
       console.log(file);
    };
    fetchBgImg = (url, load, error, progress, abort, headers) => {
        console.log('url', url);
    }

......
......
......
<FilePond
                                        ref={ref => (this.pond = ref)}
                                        oninit={() => this.handleInit()}
                                        allowMultiple={true}
                                        allowFileTypeValidation={true}
                                        acceptedFileTypes={['image/*']}
                                        labelFileTypeNotAllowed='Invalid File'
                                        files={this.state.files}                                        
                                        server={{
                                            process: this.uploadImage,
                                            fetch: this.fetchBgImg
                                        }} />`

In above snippet uploadImage is getting called but fetchBgImg is not calling.

fetch method should call fetchBgImg.

| Environment  | Version
|------------- | -----------
| OS           | Windows10 64-bit
| Device       -
| Browser      | Chrome  72.0.3626.119

**Comment by rikschennink** [comment]
fetch is called when dropping URLs of remote images I'm not sure if that is what you're expecting.
