### ISSUE TITLE
Methods addFile, addFiles class FilePond have incorrect type and signature 

### ISSUE THREAD

**Issue by OrionArm** [pqina/react-filepond#74]
I think methods addFile, addFiles have incorrect type and signature.  
Accoring to [Adding files](https://pqina.nl/filepond/docs/patterns/api/filepond-instance/) 
Both methods accept the following file references:
Local and Remote URLs
DataURLs
Blobs or File objects
Also, theese methods have second parameter (options).

But in our d.ts file has next signature:  addFile: (source: File) => void;

**Comment by rikschennink** [comment]
Then I would advise to update the d.ts file

**Comment by OrionArm** [comment]
I use  "@types/react-filepond": "^5.0.2" it is latest version
It is written there: Type definitions for react-filepond 5.0 :(

**Comment by rikschennink** [comment]
I'm not very familiar with TypeScript so I don't know how these are maintained. I would find the original maintainer and submit a PR
