### ISSUE TITLE
acceptedFileTypes props is not working

### ISSUE THREAD

**Issue by dafapramudya** [pqina/react-filepond#79]
### Summary

So i want to make format validation in react-filepond. I just want the user only can upload csv file, Right now i'm using acceptedFileTypes props, but it's not working.

### How to reproduce

Idk if it's bug or not

### Expected behaviour

Users can only upload .csv files

### Additional information

Here is my code now:
https://gist.github.com/dafapramudya/859f3d2eba94ceac91e178ab19e83105

| Environment  | Version
|------------- | -----------
| OS           | Windows
| Device       | -
| Browser      | Chrome

**Comment by rikschennink** [comment]
https://github.com/pqina/filepond-plugin-file-validate-type/issues/2

**Comment by dafapramudya** [comment]
hi @rikschennink i already test it with: acceptedFileTypes="text/csv, application/csv" but still not working. ( the choices still All Files ). And i already check the mime type too, in here: https://codepen.io/rikschennink/details/NzRvbj/

**Comment by rikschennink** [comment]
Windows doesn't filter the file types so you can still select all files.

**Comment by dafapramudya** [comment]
hmm i see. OK i'll test it on a different OS. ty

**Comment by aaveidt** [comment]
doesn't work on MacOS, chrome too.
