### ISSUE TITLE
File name label after upload

### ISSUE THREAD

**Issue by mawiza** [pqina/react-filepond#8]
How can I change the file name label after uploading the file. I don't use the file name to download the file from the server, I use an ID. 

<img width="575" alt="screen shot 2018-06-01 at 09 58 39" src="https://user-images.githubusercontent.com/7588/40840291-546afb36-65a6-11e8-928b-11bd6a7fae7c.png">

For example:

<File key={result[0]} source={result[0]} type={'local'} />

where result[0] is the id and result[1] is the filename.

Thanks in advance

**Comment by rikschennink** [comment]
If you have the name of the file on the server you can return the name in a response header. So as you're requesting local files you can adjust the api `load` end point. Adding the following header should work.

```
Content-Disposition: inline; filename=my-file.jpg
```
