### ISSUE TITLE
`onremovefile` is giving `null` for the `file` param

### ISSUE THREAD

**Issue by ivanasetiawan** [pqina/react-filepond#80]
### Summary
I am using Filepond React. 

I'd like to do an `action` when a file is removed, thus I use `onremovefile={this.handleRemove}`, however the `file` returns to `null`. 

I'd like to know which file is being removed. Should I approach this differently?

### How to reproduce
Nothing special with my implementation, I followed the doc `<Filepond onremovefile={(file) => this.handleRemove(file)} />`

### Expected behaviour
`onremovefile` should give me the `file` I deleted.

| Environment  | Version
|------------- | -----------
| OS           | MacOS
| Browser      | FF Developer Edition 67.0b6

**Comment by rikschennink** [comment]
I think the first parameter is a possible error response and the second one is the file item, can you give that a try.

**Comment by ivanasetiawan** [comment]
@rikschennink YASH! awesome thank you!

**Comment by rikschennink** [comment]
This is the repo used for the docs, PRs are very welcome. 😊
https://github.com/pqina/filepond-docs

**Comment by BjoernRave** [comment]
The typescript types are not yet reflecting this, I would update them myself but not sure how to do it with definitelytyped

**Comment by rikschennink** [comment]
@BjoernRave I don't manage those so not sure either
