### ISSUE TITLE
onprocessfiles is not working with React

### ISSUE THREAD

**Issue by ruchi1234** [pqina/react-filepond#81]
I am trying to enable and disable the submit button of form while files are uploading. I try onprocessfiles in React. But it is not working. I think this callback is not calling. It is also not giving any errror as well.

Please help.

**Comment by rikschennink** [comment]
Happy to take a look. Please provide a test case.

**Comment by Brian611** [comment]
I am facing the same issue. onprocessfile does not work for react

**Comment by Brian611** [comment]
import { FilePond, registerPlugin } from 'react-filepond';
import 'filepond/dist/filepond.min.css';
import FilePondPluginImagePreview from 'filepond-plugin-image-preview';
import 'filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.css';
import FilePondPluginFileValidateSize from 'filepond-plugin-file-validate-size';

registerPlugin(FilePondPluginImagePreview, FilePondPluginFileValidateSize);

process = (error: any, file: any) => {
        console.log('in here');

        if (error) {
            console.log('Oh no', error);
            return;
        }
        console.log('File added', file);
    };


render() {
        return (
            <>
                    <FilePond onprocessfile={this.process} name="file" maxFileSize="5MB" />
            </>
        );
    }

// file uploads just fine but i do not get any logs from that process method i created.

**Comment by rikschennink** [comment]
Please format your code snippet, a test case on [codesandbox](https://codesandbox.io/) would be appreciated.
