### ISSUE TITLE
onactivatefile callback

### ISSUE THREAD

**Issue by mylnikovD** [pqina/react-filepond#82]
Hello and thanks for such an awesome library, however, it seems that it's an issue with onactivatefile callback. 
I'm using typescript and DefinitelyTyped for filepond and it tells me about all the other callbacks in options (oninit, onaddfile etc.) but there is no onactivatefile. When I still adding this callback to filepond instance overriding the type checking it still doesn't work.  

By the way documentation is not clear whether this callback is fired when clicking on file preview, or on something else related to file. Maybe there is something else to handle clicks on image preview? 
Thanks in advance for help

**Comment by rikschennink** [comment]
Hi, a click on the file should be caught. I can look into this later this week.

You can notify the author of the type file that the file needs an update.

**Comment by rikschennink** [comment]
I just tested and this will log `'hello'` to the console when the file item is clicked. Click handling works on the preview image itself as well.

Latest version of all plugins.

```jsx
<FilePond ref={ref => this.pond = ref}
        files={this.state.files}
        allowMultiple={true}
        onactivatefile={() => console.log('hello')}>
</FilePond>
```

**Comment by mylnikovD** [comment]
Ok, it seems that my version of filepond was outdated.
Thanks a lot for your help nevertheless!
