### ISSUE TITLE
maxFiles incorrect when dragging and dropping directories

### ISSUE THREAD

**Issue by mehri-amin** [pqina/react-filepond#83]
### Summary
When I set my maxFiles as either 50 or 100, and then I proceed to drag and drop a folder with 50 or 100 files inside, it rejects the upload saying max exceeded. I think the miscount could possibly be coming from counting the directory as a file ? 

### How to reproduce
Set maxFile as either 50 or 100, it seems to work for smaller numbers like 10, but then stops working around a limit like 40 onwards. Drag and drop a folder containing same amount as maxFiles. 

### Expected behaviour
Upload all files in the directory since it's not exceeding maxFile limit. 

### Additional information
react-filepond version 7.0.1

| Environment  | Version
|------------- | -----------
| OS           | MacOS / 
| Browser      | Google Chrome Version 72.0.3626.121

**Comment by rikschennink** [comment]
Are you sure there are no hidden files in the folder.

**Comment by mehri-amin** [comment]
Sorry for late reply, this didn't solve the issue. The hidden files are ignored correctly.

**Comment by rikschennink** [comment]
Should be fixed in `4.4.7`

**Comment by mehri-amin** [comment]
The version I have is 7.0.1 though....?

**Comment by rikschennink** [comment]
The React wrapper has not changed, you can update the FilePond core library independently.

`npm install filepond@latest`
