### ISSUE TITLE
Disable / Enable breaks browser functionallity

### ISSUE THREAD

**Issue by mrsamse** [pqina/react-filepond#84]
### Summary
If I disable and renable the component via props: disable={true}, disable={false} the user can't choose a file from the filesystem anymore. He still can drag a file into filepond, but simple not choose one. I had a look at chrome dev tools and found the error. First there is a input  type='file' element. Then I disable the filepond and it's not here anymore. Thats fine for me, but after I reenable the filepond component, the is a SPAN inserted and not the input anymore. Have a look at these screenshots:

Before the disable:
![before-disable](https://user-images.githubusercontent.com/20925205/56076828-932b0c80-5dd5-11e9-80f3-14a358afe093.PNG)

After the reenable:
![after-reenable](https://user-images.githubusercontent.com/20925205/56076834-a047fb80-5dd5-11e9-863a-b30c8ae71d21.PNG)

### How to reproduce
Just disable and reenable die filpond component and you won't be able to select files from the filesystem.

| Environment  | Version
|------------- | -----------
| OS           | Windows
| Browser     | Chrome v73

**Comment by rikschennink** [comment]
Have you updated to the latest version of FilePond? This bug has recently been fixed.

**Comment by mrsamse** [comment]
Thank you! Didn't know that.
