### ISSUE TITLE
Transferring state from one component to an other clears metadata

### ISSUE THREAD

**Issue by mrsamse** [pqina/react-filepond#85]
### Summary
I have two seperate filepond components on my page for german and english. The user can upload the files to the german filepond component and after the form is posted to the server the whole state from the german form is trasferred to the english form. That works great but the problem is, that the metadata is reseted when I simply transfer the state.

Please note, that I use the File objects in my state (https://pqina.nl/filepond/docs/patterns/api/file/) and do not convert them to simple objects like in the examples.

### How to reproduce
1. Have 2 react filepond components.
2. Add a file to the first filepond component.
3. Add metadata to that file.
4. Get the state from that componet and transfer it to the second component.
5. The metadata is empty.

### Expected behaviour
The second component should have exactly the same files with the same metadata.

### Additional information
I have a "onupdatefiles" listener. So when the user adds a file I set all all files to the state. I noticed that this listener is called in the second componet when I set the files from the previous component via setState. The function parameter "files" has the correct files, but not the correct metadata.

| Environment  | Version
|------------- | -----------
| OS           | Windows
| Browser      | Chome v73

**Comment by rikschennink** [comment]
This function currently only maps the file object, you'd have to adjust it so it also includes the metadata. I think that should solve the issue.
```js
this.setState({
    files: fileItems.map(fileItem => fileItem.file)
});
```
