### ISSUE TITLE
Can't get files onupdatefiles?

### ISSUE THREAD

**Issue by yaharga** [pqina/react-filepond#87]
### Summary
I'm simply trying to get the files objects stringified. I'm using the official demo and I still can't do it.

### How to reproduce
I forked the official demo to here: https://codesandbox.io/s/j2wm3w34v9

### Expected behaviour
Get the properties to show up?

### Additional information

| Environment  | Version
|------------- | -----------
| OS           | MacOS
| Device       | MacBook Pro
| Browser      | Chrome Canary

**Comment by rikschennink** [comment]
I think it's not possible to stringify complex objects, so there for it doesn't render?

This works:
```js
function App() {
  const [files, setFiles] = useState([]);
  return (
    <div className="App">
      <FilePond
        files={files}
        allowMultiple={true}
        onupdatefiles={setFiles}
        labelIdle='Drag & Drop your files or <span class="filepond--label-action">Browse</span>'
      />
      <p>{JSON.stringify(files)}</p>
      <p>{console.log(files)}</p>
      <p>{files.map(item => item.file.name).join(',')}</p>
    </div>
  );
}
```
