### ISSUE TITLE
Potential memory leak when I try to use this in production inside custom modal

### ISSUE THREAD

**Issue by stefanomartinengo** [pqina/react-filepond#88]
### Summary
In production, the FilePond instance seems to break my entire page when initializing it inside of a custom modal. The standard gray box appears but not the text inside it. This works perfectly locally, but after pushing it into production, anytime I try to use it, the tab on the browser ends up freezing and I have to close out of it. I am thinking it is a memory leak potentially.
### How to reproduce
```
// Right after my 'getDerivedStateFromProps and componentDidMount' I have the handle init function:
	handleInit() {
		console.log('FilePond instance has initialised', this.pond);
	}
.
.
.
return (
...
...
...
<Modal
    state={this.state.modalState}
    title="Upload File"
    close={this.closeModal}
>
	<FilePond
		ref={ref => (this.pond = ref)}
		files={this.state.files}
		allowMultiple={true}
		maxFiles={10}
		name="documents"
		oninit={() => this.handleInit()}
		server={{
			process: {
	      		    url:
				'/api/v1/upload/' +
				this.props.contact.uuid +
				'/' +
				this.props.org_uuid,
			method: 'POST',
			onload: file => this.props.uploadContactFile(JSON.parse(file).values),
				headers: {
				authorization: this.state.user,
				},
				onerror: () => alert('unable to upload this document'),
				},
				}}
			allowRevert={false}
			onwarning={error => this.handleError(error)}
			onupdatefiles={fileItems => {
				this.setState({
					files: fileItems.map(fileItem => fileItem.file),
				});
			}}
		/>
</Modal>
)
```

### Additional information
Create React App running react version: 16.5.2
filepond: 4.3.5
react-filepond: 7.0.1
 Node on Develop: 10.15.3 
Node on Production: 8.11.4 
(Could the big difference i node versions cause this issue?)
My nodejs upload middleware is multer and multer-s3

My node server that is listening for that endpoint, is returning the filekey/s3-path and a status of 200 after uploading to S3 for me to capture on the front-end

**Comment by rikschennink** [comment]
Closed because double post.
https://stackoverflow.com/questions/55818570/is-this-a-memory-leak-using-react-filepond
