### ISSUE TITLE
`onerror` handler not returning server error

### ISSUE THREAD

**Issue by varunpatro** [pqina/react-filepond#89]
### Summary

When the server responds with a 400 request with some useful message in the body, I want to be able to access the body of the response sent by the server. 

### Expected behaviour

Right now, I rely on the `onerror` callback. The first argument to the callback is the `err` object with the params: `code` and `body`. If `code` is `400` then `body` is automatically `Bad request`. Instead the body should be the body returned by the server.

### Additional information

| Environment  | Version
|------------- | -----------
| OS           | MacOS 
| Device       | Macbook Air
| Browser      | Firefox 66

**Comment by varunpatro** [comment]
@yongjieyongjie

**Comment by stefanomartinengo** [comment]
Can you show your code so I can get an idea of how you are going about this?

**Comment by rikschennink** [comment]
Use the `onerror` callback on the `server.process` object to filter the server error response.
https://pqina.nl/filepond/docs/patterns/api/server/#configuration

**Comment by porluz** [comment]
How would you then get the status code to know what type of error from the server process? That only returns the error and nothing else.

**Comment by rikschennink** [comment]
The error object automatically contains the status code, see example here:
https://codesandbox.io/s/vanilla-filepond-dynamic-process-file-error-nji1n
