### ISSUE TITLE
Name passing as empty object using an instance. 

### ISSUE THREAD

**Issue by mazer-rakham** [pqina/react-filepond#90]
Hello, 
Using refs on FilePond instances creates an empty name object on the input. In my component:
```js 
 submitImages = (fieldName) => {
    const formData = new FormData();  
    this.pond.getFiles()
      .map(fileItem => fileItem.file)
      .forEach(file => {   
        formData.append(fieldName, file, file.name);        
      });
      console.log(formData);
     this.props.addUserPhoto(formData);
      
  }

// stuff here
 <Form onSubmit={this.submitImages}>
    <Form.Field>
        <FilePond ref={ref => this.pond = ref} name="userphoto" />
     </Form.Field>
      <Form.Field>
        <Button type="submit">submit</Button>
      </Form.Field>
</Form>
```

Sends an name="[object Object]" in the Form Data request and the backend, attached screenshot. 
![image](https://user-images.githubusercontent.com/11220261/56992609-6f531f00-6b68-11e9-9cb8-28af2caa29e6.png)

**Comment by rikschennink** [comment]
You're referencing `submitImages` in your `onSubmit` callback, `fieldName` will be an `event` object, and you're using it as the field name in the `formData` object, therefor it's an `[object Object]`.

The issue is not related to FilePond.
