### ISSUE TITLE
Upload button with Base64 support

### ISSUE THREAD

**Issue by Ryukote** [pqina/react-filepond#91]
Is it possible to use this component in a way that user first drag and drop for example 3 images and when he press the button that is separate from this component, application is uploading programatically to somewhere image by image? And with that to remove upload button on each image?

Bonus question, so I don't need to open another issue, how does this component upload an image? As Base64 or something else? If something else, is it possible to upload as a Base64?

Thank you.

**Comment by rikschennink** [comment]
Please thorougly read the documentation, you should be able to judge from the docs if the above is possible or not.

If you upload asynchronously you can upload files as file objects, if you want to send files along with a form post you need to use the file encode plugin which turns the files into base64 strings.

**Comment by Ryukote** [comment]
Thank you.
