### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by zakariafik** [pqina/react-filepond#92]
Hey,

First, I would like to thank you for the amazing job you've done.
I was wondering if there is a way to include pagination to the file upload (case where we upload a lot of files and want to display them in separate pages rather than use scrolling to reach it)?

Thank you!

**Comment by rikschennink** [comment]
Hi, Thanks! That would require a total rewrite of the component. It's currently for from flexible enough to allow this. You could introduce multiple FilePond instances to mimic the behaviour.
