### ISSUE TITLE
IE-11 'onremovefile' not triggered on click of remove icon

### ISSUE THREAD

**Issue by raghu1286** [pqina/react-filepond#93]
Hi,

On IE11 the ```onremovefile``` callback is not being triggered. The file is uploaded successfully, after that on click of the remove icon nothing happens, no error in console either. Tried the ```onerror``` callback as well, not being triggered. On other browsers its working fine.

The callback ```beforeRemoveFile``` is being triggered.

I've included  filepond-polyfill as well with no luck.

Any inputs are appreciated.

Thanks!

**Comment by calinchiper** [comment]
@raghu1286 I also reproduced using angular wrapper library. I think it's a general problem from the core library.

**Comment by rikschennink** [comment]
Setting `server.revert` to `null` should solve the issue

**Comment by calinchiper** [comment]
@rikschennink Yes. Seems working right now.

**Comment by raghu1286** [comment]
@rikschennink - Can confirm its working with React as well. 
Thanks for the fix!
