### ISSUE TITLE
Dragging and dropping directory of 100 files skips a file

### ISSUE THREAD

**Issue by mehri-amin** [pqina/react-filepond#94]
### Summary
When I drag and drop a folder containing 100 files it only takes 99 of the files, the one it misses seems arbitrary? When I select all the individual files and drag and drop it works perfectly fine so it seems unique to directories. I've checked if there are any hidden files, there's only one .DS_Store and that is being ignored correctly. A directory with less files, say 50, works fine, it seems to only happen with 100 files. 

### How to reproduce
Drag and drop a folder containing 100 files [file types: png, pdf, jpg]

### Expected behaviour
Upload all 100 files.

### Additional information

| Environment  | Version
|------------- | -----------
| OS           | MacOS 
| Device       | Macbook Pro 2017
| Browser      | Google Chrome
| react-filepond | 7.0.1
|filepond | 4.4.7

**Comment by rikschennink** [comment]
It's best to open these issues in the FilePond core repository 👉 https://github.com/pqina/filepond as they are probably not related to React.

Please provide a test case that reproduces the issue. For example a zip with a selection of test files (for instance, 1 byte txt's)

**Comment by rikschennink** [comment]
Closed as inactive since May 24th
