### ISSUE TITLE
Pre filled image

### ISSUE THREAD

**Issue by mhmmdakbr** [pqina/react-filepond#95]
### Summary
I try to follow the step on filepond documentation but i'm confused because i'm using React and
this is my code for server options : 
```javascript
             server={{
                   fetch: 'http://localhost:3333/uploads/avatar/${detailUser.Avatar}',
                   process: {
                     url: "api/v1/uploadAvatar",
                     method: 'POST',
                     onload: (response) => this.state.photo.push(JSON.parse(response).fileName),
                   },
                   load: 'http://localhost:3333/uploads/avatar/${detailUser.Avatar}'
              }}
```

this is my code for files : 
```javascript
             files={this.state.files === []? [
                  {
                      // the server file reference
                     source: 'http://localhost:3333/uploads/avatar/${detailUser.Avatar}',
                    
                     // set type to limbo to tell FilePond this is a temp file
                     options: {
                     type: 'local'
                     }
                 }
              ]: this.state.files
            }
```

hopefully  this can help you

### Expected behaviour
So i want to make an edit page for profile like github, it has an prefilled image in profile picture before you edited it. And the image is already on the server

sorry for my bad english

**Comment by rikschennink** [comment]
I'm not sure but it seems the problem description is missing.

**Comment by mhmmdakbr** [comment]
> I'm not sure but it seems the problem description is missing.

So the problem is i want to prefilled the image ( something like the github profile page ) , I successfully uploaded to my localhost ( path : localhost:3333/uploads/avatar ). But when i want to fetch it , it fails. i've tried to followed all your documentation that you've been created.

**Comment by rikschennink** [comment]
`server.fetch` is only used to load remote images (image on other servers) you need to use the `server.load` end point to load local (already stored) images.

**Comment by rikschennink** [comment]
Closed as inactive since Jun 18th
