### ISSUE TITLE
Speed of uploading animation?

### ISSUE THREAD

**Issue by indefinitelee** [pqina/react-filepond#96]
Is there any API to control the speed of the uploading animation in react-filepond?
Occasionally my server is responding with success/error message before the animation is complete. 

I would appreciate if you could refer to documentation hosted on github as I can't access pqina.nl 

Thanks

**Comment by rikschennink** [comment]
The upload animation speed is fixed. It always shows a simulated upload duration so the user can see it actually uploading the file (even if it's already on the server).

@indefinitelee Why can't you access pqina.nl ?

**Comment by indefinitelee** [comment]
Thanks Rik. 

Pqina is blacklisted by corporate firewall.

**Comment by rikschennink** [comment]
@indefinitelee okay thanks, was kinda worried for a moment there :-)
