### ISSUE TITLE
Filepond stored empty in the the db.

### ISSUE THREAD

**Issue by JavierPons** [pqina/react-filepond#97]
Hello fellow developer!

💡 If you want to submit a feature request, go right ahead!

🐜 If you've found a bug, please use the template below to report it.

**The more details you provide, the more inclined other developers are to help you and the faster the problem is resolved.**

If you think the issue is related FilePond itself and not the React framework or adapter, please submit the issue in the FilePond repository.

Please format code snippets using backticks and don't forget to set the appropriate language.
https://help.github.com/articles/creating-and-highlighting-code-blocks/

### Additional information

| Environment  | Version
|------------- | -----------
| OS           | MacOS / Windows / iOS / Linux / ...
| Device       | iPhone SE / Galaxy Note 9 / ...
| Browser      | Safari 11.1.1 / Edge 15 / ...

**Comment by JavierPons** [comment]
Hi thank you for FilePond it is cool.

I have added <FilePond /> to my component like this 
` <Fragment>
      <form action="/upload" encType="multipart/form-data" className="form-up">
        <div className="form-group">
          <label htmlFor="name">Test title</label>

          <input
            className="form-control"
            type="text"
            id="name"
            name="title"
            value={file.title}
            onChange={e => {
              console.log("this is file =>", file);
              handleForm(e, file, setFileVal);
            }}
            // placeholder={profile.username}
          />
        </div>
        <div className="form-group">
          <FilePond
            allowMultiple={false}
            file={file}
            server="http://localhost:3008/api/test"
            onupdatefiles={fileItems => {
              console.log("here");
              setFileVal({
                title: file.title,
                file: fileItems
              });
            }}
          />

          <button
            className="btn btn-success btn-block"
            type="button"
            onClick={() => {
              console.log("This is file.title   **??**>", file.title, "This is file.file ===>", file.file);
              onfile(file.title, file.file);
            }}
          >
            Upload file
          </button>
        </div>
      </form>
    </Fragment>
`

when is clicked online do this.  =====>
` const onfile = (title, file) => {
    console.log("Only title ====>", title);

    const obj = {
      title: title,
      file: file
    };
    console.log("this is files *** == *** >", obj);
    axios
      .post("http://localhost:3008/api/test", obj)
      .then(res => console.log("This is data =>", res.data, "this is obj>", obj, "This is my fileeee", obj.file))
      .catch(function(err) {
        console.log(err);
      });
  };`

The issues:

1.- Main issue. If I browse first and upload a file automatically store it in my MongoDB db without name, let call A.
and still being saved the same file in FilePond I type title and then click button, it store in the db the name and file, let call B. Two stores in db.

In the console.log this is files *** == *** I can see there getMetadata and the name of file, size, etc. but the serverId id from setMetadata is the id of the first called A. why? And in console.log This is data =>  array doesn't have setMetadata and anything, it's empty.

I want that when I type title and then click, only store in db ones with the setMetadata that I can access later.

Any support, help, view or something  that I didn't see or understand, please let me know. 

2.-THIS Other issue, other way:
 If I type title and then browse and upload file. ==> the title disappear and don't become registered. Only save the file and I can get it later and manipulate. 


Browser  Chorme Version 75.0.3770.100 (Official Build) (64-bit)
MacBook Pro (Retina, 15-inch, Mid 2014) 
macOS Mojave. Version 10.14.5

**Comment by rikschennink** [comment]
I'm sorry, because of the malformed code snippets and unformatted text snippets I don't know what's going on.

**Comment by JavierPons** [comment]
Oh thank you. Issue is solve.
