### ISSUE TITLE
imagePreviewMaxHeight not working for poster image height

### ISSUE THREAD

**Issue by nehadhiman6** [pqina/react-filepond#98]
Hello fellow developer!
i am using filpond with Vuejs. imagePreviewMaxHeight is working fine. but when i use poster in edit case  image PreviewMaxHeight is not working.

### Summary

 myFiles.push({
             source:base_url+'/attachments/'+user.user_attachable.attachment_id,
             options:{
                          type:'local',
                          metadata: {
                          poster: base_url+'/attachments/'+user.user_attachable.attachment_id
                          },
            },
});

 <file-pond
    ref="pond"
    :imagePreviewMaxHeight="50"
    labelIdle =  'Drag & drop your picture here'
    style-panel-layout="compact circle"
    accepted-file-types = "image/jpeg, image/png"
    v-bind:server="{
        url: base_url,
        timeout: 7000,
        process: {
            url: '/attachments',
            method: 'POST',
            headers: {
                'X-CSRF-TOKEN':token
            },
            withCredentials: false,
            onload: onResponse,

        },
        //   revert: '/attachments/'+form.attachment_id // or null
        revert: null
    }"
    :files="myFiles"

    >
</file-pond>
with normal Upload:

![filepond2](https://user-images.githubusercontent.com/52815432/61110152-34446480-a4a4-11e9-9ac4-fa8eb094503c.png)

with initial Poster images:

![filepond1](https://user-images.githubusercontent.com/52815432/61110077-09f2a700-a4a4-11e9-91e9-39eedf2b8b0f.png)

**Comment by rikschennink** [comment]
Please don't double post.
https://github.com/pqina/vue-filepond/issues/94
